package com.example.dao.mapper;

import com.example.dao.entity.Armgstatus;
import com.example.dao.entity.ArmgstatusExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ArmgstatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    long countByExample(ArmgstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    int deleteByExample(ArmgstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    int deleteByPrimaryKey(String armgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    int insert(Armgstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    int insertSelective(Armgstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    List<Armgstatus> selectByExample(ArmgstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    Armgstatus selectByPrimaryKey(String armgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") Armgstatus record, @Param("example") ArmgstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    int updateByExample(@Param("record") Armgstatus record, @Param("example") ArmgstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(Armgstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    int updateByPrimaryKey(Armgstatus record);
}