package com.example.dao.mapper;

import com.example.dao.entity.Armgslottos;
import com.example.dao.entity.ArmgslottosExample;
import com.example.dao.entity.ArmgslottosKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ArmgslottosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTTOS
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    long countByExample(ArmgslottosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTTOS
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    int deleteByExample(ArmgslottosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTTOS
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    int deleteByPrimaryKey(ArmgslottosKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTTOS
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    int insert(Armgslottos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTTOS
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    int insertSelective(Armgslottos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTTOS
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    List<Armgslottos> selectByExample(ArmgslottosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTTOS
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    Armgslottos selectByPrimaryKey(ArmgslottosKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTTOS
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") Armgslottos record, @Param("example") ArmgslottosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTTOS
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    int updateByExample(@Param("record") Armgslottos record, @Param("example") ArmgslottosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTTOS
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(Armgslottos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTTOS
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    int updateByPrimaryKey(Armgslottos record);
}