package com.example.dao.mapper;

import com.example.dao.entity.Armgjobq;
import com.example.dao.entity.ArmgjobqExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ArmgjobqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    long countByExample(ArmgjobqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    int deleteByExample(ArmgjobqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Long jobOrderSeqMs);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    int insert(Armgjobq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    int insertSelective(Armgjobq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    List<Armgjobq> selectByExample(ArmgjobqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    Armgjobq selectByPrimaryKey(Long jobOrderSeqMs);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") Armgjobq record, @Param("example") ArmgjobqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    int updateByExample(@Param("record") Armgjobq record, @Param("example") ArmgjobqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(Armgjobq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    int updateByPrimaryKey(Armgjobq record);
}