package com.example.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ArmgstatusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public ArmgstatusExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andArmgIdIsNull() {
            addCriterion("ARMG_ID is null");
            return (Criteria) this;
        }

        public Criteria andArmgIdIsNotNull() {
            addCriterion("ARMG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andArmgIdEqualTo(String value) {
            addCriterion("ARMG_ID =", value, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdNotEqualTo(String value) {
            addCriterion("ARMG_ID <>", value, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdGreaterThan(String value) {
            addCriterion("ARMG_ID >", value, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdGreaterThanOrEqualTo(String value) {
            addCriterion("ARMG_ID >=", value, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdLessThan(String value) {
            addCriterion("ARMG_ID <", value, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdLessThanOrEqualTo(String value) {
            addCriterion("ARMG_ID <=", value, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdLike(String value) {
            addCriterion("ARMG_ID like", value, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdNotLike(String value) {
            addCriterion("ARMG_ID not like", value, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdIn(List<String> values) {
            addCriterion("ARMG_ID in", values, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdNotIn(List<String> values) {
            addCriterion("ARMG_ID not in", values, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdBetween(String value1, String value2) {
            addCriterion("ARMG_ID between", value1, value2, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdNotBetween(String value1, String value2) {
            addCriterion("ARMG_ID not between", value1, value2, "armgId");
            return (Criteria) this;
        }

        public Criteria andManIntervenIsNull() {
            addCriterion("MAN_INTERVEN is null");
            return (Criteria) this;
        }

        public Criteria andManIntervenIsNotNull() {
            addCriterion("MAN_INTERVEN is not null");
            return (Criteria) this;
        }

        public Criteria andManIntervenEqualTo(Short value) {
            addCriterion("MAN_INTERVEN =", value, "manInterven");
            return (Criteria) this;
        }

        public Criteria andManIntervenNotEqualTo(Short value) {
            addCriterion("MAN_INTERVEN <>", value, "manInterven");
            return (Criteria) this;
        }

        public Criteria andManIntervenGreaterThan(Short value) {
            addCriterion("MAN_INTERVEN >", value, "manInterven");
            return (Criteria) this;
        }

        public Criteria andManIntervenGreaterThanOrEqualTo(Short value) {
            addCriterion("MAN_INTERVEN >=", value, "manInterven");
            return (Criteria) this;
        }

        public Criteria andManIntervenLessThan(Short value) {
            addCriterion("MAN_INTERVEN <", value, "manInterven");
            return (Criteria) this;
        }

        public Criteria andManIntervenLessThanOrEqualTo(Short value) {
            addCriterion("MAN_INTERVEN <=", value, "manInterven");
            return (Criteria) this;
        }

        public Criteria andManIntervenIn(List<Short> values) {
            addCriterion("MAN_INTERVEN in", values, "manInterven");
            return (Criteria) this;
        }

        public Criteria andManIntervenNotIn(List<Short> values) {
            addCriterion("MAN_INTERVEN not in", values, "manInterven");
            return (Criteria) this;
        }

        public Criteria andManIntervenBetween(Short value1, Short value2) {
            addCriterion("MAN_INTERVEN between", value1, value2, "manInterven");
            return (Criteria) this;
        }

        public Criteria andManIntervenNotBetween(Short value1, Short value2) {
            addCriterion("MAN_INTERVEN not between", value1, value2, "manInterven");
            return (Criteria) this;
        }

        public Criteria andWaitingTypeIsNull() {
            addCriterion("WAITING_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andWaitingTypeIsNotNull() {
            addCriterion("WAITING_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andWaitingTypeEqualTo(Short value) {
            addCriterion("WAITING_TYPE =", value, "waitingType");
            return (Criteria) this;
        }

        public Criteria andWaitingTypeNotEqualTo(Short value) {
            addCriterion("WAITING_TYPE <>", value, "waitingType");
            return (Criteria) this;
        }

        public Criteria andWaitingTypeGreaterThan(Short value) {
            addCriterion("WAITING_TYPE >", value, "waitingType");
            return (Criteria) this;
        }

        public Criteria andWaitingTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("WAITING_TYPE >=", value, "waitingType");
            return (Criteria) this;
        }

        public Criteria andWaitingTypeLessThan(Short value) {
            addCriterion("WAITING_TYPE <", value, "waitingType");
            return (Criteria) this;
        }

        public Criteria andWaitingTypeLessThanOrEqualTo(Short value) {
            addCriterion("WAITING_TYPE <=", value, "waitingType");
            return (Criteria) this;
        }

        public Criteria andWaitingTypeIn(List<Short> values) {
            addCriterion("WAITING_TYPE in", values, "waitingType");
            return (Criteria) this;
        }

        public Criteria andWaitingTypeNotIn(List<Short> values) {
            addCriterion("WAITING_TYPE not in", values, "waitingType");
            return (Criteria) this;
        }

        public Criteria andWaitingTypeBetween(Short value1, Short value2) {
            addCriterion("WAITING_TYPE between", value1, value2, "waitingType");
            return (Criteria) this;
        }

        public Criteria andWaitingTypeNotBetween(Short value1, Short value2) {
            addCriterion("WAITING_TYPE not between", value1, value2, "waitingType");
            return (Criteria) this;
        }

        public Criteria andOperationModeIsNull() {
            addCriterion("OPERATION_MODE is null");
            return (Criteria) this;
        }

        public Criteria andOperationModeIsNotNull() {
            addCriterion("OPERATION_MODE is not null");
            return (Criteria) this;
        }

        public Criteria andOperationModeEqualTo(Short value) {
            addCriterion("OPERATION_MODE =", value, "operationMode");
            return (Criteria) this;
        }

        public Criteria andOperationModeNotEqualTo(Short value) {
            addCriterion("OPERATION_MODE <>", value, "operationMode");
            return (Criteria) this;
        }

        public Criteria andOperationModeGreaterThan(Short value) {
            addCriterion("OPERATION_MODE >", value, "operationMode");
            return (Criteria) this;
        }

        public Criteria andOperationModeGreaterThanOrEqualTo(Short value) {
            addCriterion("OPERATION_MODE >=", value, "operationMode");
            return (Criteria) this;
        }

        public Criteria andOperationModeLessThan(Short value) {
            addCriterion("OPERATION_MODE <", value, "operationMode");
            return (Criteria) this;
        }

        public Criteria andOperationModeLessThanOrEqualTo(Short value) {
            addCriterion("OPERATION_MODE <=", value, "operationMode");
            return (Criteria) this;
        }

        public Criteria andOperationModeIn(List<Short> values) {
            addCriterion("OPERATION_MODE in", values, "operationMode");
            return (Criteria) this;
        }

        public Criteria andOperationModeNotIn(List<Short> values) {
            addCriterion("OPERATION_MODE not in", values, "operationMode");
            return (Criteria) this;
        }

        public Criteria andOperationModeBetween(Short value1, Short value2) {
            addCriterion("OPERATION_MODE between", value1, value2, "operationMode");
            return (Criteria) this;
        }

        public Criteria andOperationModeNotBetween(Short value1, Short value2) {
            addCriterion("OPERATION_MODE not between", value1, value2, "operationMode");
            return (Criteria) this;
        }

        public Criteria andAutoStatusIsNull() {
            addCriterion("AUTO_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andAutoStatusIsNotNull() {
            addCriterion("AUTO_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andAutoStatusEqualTo(Short value) {
            addCriterion("AUTO_STATUS =", value, "autoStatus");
            return (Criteria) this;
        }

        public Criteria andAutoStatusNotEqualTo(Short value) {
            addCriterion("AUTO_STATUS <>", value, "autoStatus");
            return (Criteria) this;
        }

        public Criteria andAutoStatusGreaterThan(Short value) {
            addCriterion("AUTO_STATUS >", value, "autoStatus");
            return (Criteria) this;
        }

        public Criteria andAutoStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("AUTO_STATUS >=", value, "autoStatus");
            return (Criteria) this;
        }

        public Criteria andAutoStatusLessThan(Short value) {
            addCriterion("AUTO_STATUS <", value, "autoStatus");
            return (Criteria) this;
        }

        public Criteria andAutoStatusLessThanOrEqualTo(Short value) {
            addCriterion("AUTO_STATUS <=", value, "autoStatus");
            return (Criteria) this;
        }

        public Criteria andAutoStatusIn(List<Short> values) {
            addCriterion("AUTO_STATUS in", values, "autoStatus");
            return (Criteria) this;
        }

        public Criteria andAutoStatusNotIn(List<Short> values) {
            addCriterion("AUTO_STATUS not in", values, "autoStatus");
            return (Criteria) this;
        }

        public Criteria andAutoStatusBetween(Short value1, Short value2) {
            addCriterion("AUTO_STATUS between", value1, value2, "autoStatus");
            return (Criteria) this;
        }

        public Criteria andAutoStatusNotBetween(Short value1, Short value2) {
            addCriterion("AUTO_STATUS not between", value1, value2, "autoStatus");
            return (Criteria) this;
        }

        public Criteria andConsoleConnectedIsNull() {
            addCriterion("CONSOLE_CONNECTED is null");
            return (Criteria) this;
        }

        public Criteria andConsoleConnectedIsNotNull() {
            addCriterion("CONSOLE_CONNECTED is not null");
            return (Criteria) this;
        }

        public Criteria andConsoleConnectedEqualTo(Integer value) {
            addCriterion("CONSOLE_CONNECTED =", value, "consoleConnected");
            return (Criteria) this;
        }

        public Criteria andConsoleConnectedNotEqualTo(Integer value) {
            addCriterion("CONSOLE_CONNECTED <>", value, "consoleConnected");
            return (Criteria) this;
        }

        public Criteria andConsoleConnectedGreaterThan(Integer value) {
            addCriterion("CONSOLE_CONNECTED >", value, "consoleConnected");
            return (Criteria) this;
        }

        public Criteria andConsoleConnectedGreaterThanOrEqualTo(Integer value) {
            addCriterion("CONSOLE_CONNECTED >=", value, "consoleConnected");
            return (Criteria) this;
        }

        public Criteria andConsoleConnectedLessThan(Integer value) {
            addCriterion("CONSOLE_CONNECTED <", value, "consoleConnected");
            return (Criteria) this;
        }

        public Criteria andConsoleConnectedLessThanOrEqualTo(Integer value) {
            addCriterion("CONSOLE_CONNECTED <=", value, "consoleConnected");
            return (Criteria) this;
        }

        public Criteria andConsoleConnectedIn(List<Integer> values) {
            addCriterion("CONSOLE_CONNECTED in", values, "consoleConnected");
            return (Criteria) this;
        }

        public Criteria andConsoleConnectedNotIn(List<Integer> values) {
            addCriterion("CONSOLE_CONNECTED not in", values, "consoleConnected");
            return (Criteria) this;
        }

        public Criteria andConsoleConnectedBetween(Integer value1, Integer value2) {
            addCriterion("CONSOLE_CONNECTED between", value1, value2, "consoleConnected");
            return (Criteria) this;
        }

        public Criteria andConsoleConnectedNotBetween(Integer value1, Integer value2) {
            addCriterion("CONSOLE_CONNECTED not between", value1, value2, "consoleConnected");
            return (Criteria) this;
        }

        public Criteria andCraneOnIsNull() {
            addCriterion("CRANE_ON is null");
            return (Criteria) this;
        }

        public Criteria andCraneOnIsNotNull() {
            addCriterion("CRANE_ON is not null");
            return (Criteria) this;
        }

        public Criteria andCraneOnEqualTo(Short value) {
            addCriterion("CRANE_ON =", value, "craneOn");
            return (Criteria) this;
        }

        public Criteria andCraneOnNotEqualTo(Short value) {
            addCriterion("CRANE_ON <>", value, "craneOn");
            return (Criteria) this;
        }

        public Criteria andCraneOnGreaterThan(Short value) {
            addCriterion("CRANE_ON >", value, "craneOn");
            return (Criteria) this;
        }

        public Criteria andCraneOnGreaterThanOrEqualTo(Short value) {
            addCriterion("CRANE_ON >=", value, "craneOn");
            return (Criteria) this;
        }

        public Criteria andCraneOnLessThan(Short value) {
            addCriterion("CRANE_ON <", value, "craneOn");
            return (Criteria) this;
        }

        public Criteria andCraneOnLessThanOrEqualTo(Short value) {
            addCriterion("CRANE_ON <=", value, "craneOn");
            return (Criteria) this;
        }

        public Criteria andCraneOnIn(List<Short> values) {
            addCriterion("CRANE_ON in", values, "craneOn");
            return (Criteria) this;
        }

        public Criteria andCraneOnNotIn(List<Short> values) {
            addCriterion("CRANE_ON not in", values, "craneOn");
            return (Criteria) this;
        }

        public Criteria andCraneOnBetween(Short value1, Short value2) {
            addCriterion("CRANE_ON between", value1, value2, "craneOn");
            return (Criteria) this;
        }

        public Criteria andCraneOnNotBetween(Short value1, Short value2) {
            addCriterion("CRANE_ON not between", value1, value2, "craneOn");
            return (Criteria) this;
        }

        public Criteria andLightOnIsNull() {
            addCriterion("LIGHT_ON is null");
            return (Criteria) this;
        }

        public Criteria andLightOnIsNotNull() {
            addCriterion("LIGHT_ON is not null");
            return (Criteria) this;
        }

        public Criteria andLightOnEqualTo(Short value) {
            addCriterion("LIGHT_ON =", value, "lightOn");
            return (Criteria) this;
        }

        public Criteria andLightOnNotEqualTo(Short value) {
            addCriterion("LIGHT_ON <>", value, "lightOn");
            return (Criteria) this;
        }

        public Criteria andLightOnGreaterThan(Short value) {
            addCriterion("LIGHT_ON >", value, "lightOn");
            return (Criteria) this;
        }

        public Criteria andLightOnGreaterThanOrEqualTo(Short value) {
            addCriterion("LIGHT_ON >=", value, "lightOn");
            return (Criteria) this;
        }

        public Criteria andLightOnLessThan(Short value) {
            addCriterion("LIGHT_ON <", value, "lightOn");
            return (Criteria) this;
        }

        public Criteria andLightOnLessThanOrEqualTo(Short value) {
            addCriterion("LIGHT_ON <=", value, "lightOn");
            return (Criteria) this;
        }

        public Criteria andLightOnIn(List<Short> values) {
            addCriterion("LIGHT_ON in", values, "lightOn");
            return (Criteria) this;
        }

        public Criteria andLightOnNotIn(List<Short> values) {
            addCriterion("LIGHT_ON not in", values, "lightOn");
            return (Criteria) this;
        }

        public Criteria andLightOnBetween(Short value1, Short value2) {
            addCriterion("LIGHT_ON between", value1, value2, "lightOn");
            return (Criteria) this;
        }

        public Criteria andLightOnNotBetween(Short value1, Short value2) {
            addCriterion("LIGHT_ON not between", value1, value2, "lightOn");
            return (Criteria) this;
        }

        public Criteria andMaxSpeedIsNull() {
            addCriterion("MAX_SPEED is null");
            return (Criteria) this;
        }

        public Criteria andMaxSpeedIsNotNull() {
            addCriterion("MAX_SPEED is not null");
            return (Criteria) this;
        }

        public Criteria andMaxSpeedEqualTo(Short value) {
            addCriterion("MAX_SPEED =", value, "maxSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxSpeedNotEqualTo(Short value) {
            addCriterion("MAX_SPEED <>", value, "maxSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxSpeedGreaterThan(Short value) {
            addCriterion("MAX_SPEED >", value, "maxSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxSpeedGreaterThanOrEqualTo(Short value) {
            addCriterion("MAX_SPEED >=", value, "maxSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxSpeedLessThan(Short value) {
            addCriterion("MAX_SPEED <", value, "maxSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxSpeedLessThanOrEqualTo(Short value) {
            addCriterion("MAX_SPEED <=", value, "maxSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxSpeedIn(List<Short> values) {
            addCriterion("MAX_SPEED in", values, "maxSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxSpeedNotIn(List<Short> values) {
            addCriterion("MAX_SPEED not in", values, "maxSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxSpeedBetween(Short value1, Short value2) {
            addCriterion("MAX_SPEED between", value1, value2, "maxSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxSpeedNotBetween(Short value1, Short value2) {
            addCriterion("MAX_SPEED not between", value1, value2, "maxSpeed");
            return (Criteria) this;
        }

        public Criteria andRampRateIsNull() {
            addCriterion("RAMP_RATE is null");
            return (Criteria) this;
        }

        public Criteria andRampRateIsNotNull() {
            addCriterion("RAMP_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andRampRateEqualTo(Short value) {
            addCriterion("RAMP_RATE =", value, "rampRate");
            return (Criteria) this;
        }

        public Criteria andRampRateNotEqualTo(Short value) {
            addCriterion("RAMP_RATE <>", value, "rampRate");
            return (Criteria) this;
        }

        public Criteria andRampRateGreaterThan(Short value) {
            addCriterion("RAMP_RATE >", value, "rampRate");
            return (Criteria) this;
        }

        public Criteria andRampRateGreaterThanOrEqualTo(Short value) {
            addCriterion("RAMP_RATE >=", value, "rampRate");
            return (Criteria) this;
        }

        public Criteria andRampRateLessThan(Short value) {
            addCriterion("RAMP_RATE <", value, "rampRate");
            return (Criteria) this;
        }

        public Criteria andRampRateLessThanOrEqualTo(Short value) {
            addCriterion("RAMP_RATE <=", value, "rampRate");
            return (Criteria) this;
        }

        public Criteria andRampRateIn(List<Short> values) {
            addCriterion("RAMP_RATE in", values, "rampRate");
            return (Criteria) this;
        }

        public Criteria andRampRateNotIn(List<Short> values) {
            addCriterion("RAMP_RATE not in", values, "rampRate");
            return (Criteria) this;
        }

        public Criteria andRampRateBetween(Short value1, Short value2) {
            addCriterion("RAMP_RATE between", value1, value2, "rampRate");
            return (Criteria) this;
        }

        public Criteria andRampRateNotBetween(Short value1, Short value2) {
            addCriterion("RAMP_RATE not between", value1, value2, "rampRate");
            return (Criteria) this;
        }

        public Criteria andTpsFogModeIsNull() {
            addCriterion("TPS_FOG_MODE is null");
            return (Criteria) this;
        }

        public Criteria andTpsFogModeIsNotNull() {
            addCriterion("TPS_FOG_MODE is not null");
            return (Criteria) this;
        }

        public Criteria andTpsFogModeEqualTo(Short value) {
            addCriterion("TPS_FOG_MODE =", value, "tpsFogMode");
            return (Criteria) this;
        }

        public Criteria andTpsFogModeNotEqualTo(Short value) {
            addCriterion("TPS_FOG_MODE <>", value, "tpsFogMode");
            return (Criteria) this;
        }

        public Criteria andTpsFogModeGreaterThan(Short value) {
            addCriterion("TPS_FOG_MODE >", value, "tpsFogMode");
            return (Criteria) this;
        }

        public Criteria andTpsFogModeGreaterThanOrEqualTo(Short value) {
            addCriterion("TPS_FOG_MODE >=", value, "tpsFogMode");
            return (Criteria) this;
        }

        public Criteria andTpsFogModeLessThan(Short value) {
            addCriterion("TPS_FOG_MODE <", value, "tpsFogMode");
            return (Criteria) this;
        }

        public Criteria andTpsFogModeLessThanOrEqualTo(Short value) {
            addCriterion("TPS_FOG_MODE <=", value, "tpsFogMode");
            return (Criteria) this;
        }

        public Criteria andTpsFogModeIn(List<Short> values) {
            addCriterion("TPS_FOG_MODE in", values, "tpsFogMode");
            return (Criteria) this;
        }

        public Criteria andTpsFogModeNotIn(List<Short> values) {
            addCriterion("TPS_FOG_MODE not in", values, "tpsFogMode");
            return (Criteria) this;
        }

        public Criteria andTpsFogModeBetween(Short value1, Short value2) {
            addCriterion("TPS_FOG_MODE between", value1, value2, "tpsFogMode");
            return (Criteria) this;
        }

        public Criteria andTpsFogModeNotBetween(Short value1, Short value2) {
            addCriterion("TPS_FOG_MODE not between", value1, value2, "tpsFogMode");
            return (Criteria) this;
        }

        public Criteria andFireAlarmIndIsNull() {
            addCriterion("FIRE_ALARM_IND is null");
            return (Criteria) this;
        }

        public Criteria andFireAlarmIndIsNotNull() {
            addCriterion("FIRE_ALARM_IND is not null");
            return (Criteria) this;
        }

        public Criteria andFireAlarmIndEqualTo(Short value) {
            addCriterion("FIRE_ALARM_IND =", value, "fireAlarmInd");
            return (Criteria) this;
        }

        public Criteria andFireAlarmIndNotEqualTo(Short value) {
            addCriterion("FIRE_ALARM_IND <>", value, "fireAlarmInd");
            return (Criteria) this;
        }

        public Criteria andFireAlarmIndGreaterThan(Short value) {
            addCriterion("FIRE_ALARM_IND >", value, "fireAlarmInd");
            return (Criteria) this;
        }

        public Criteria andFireAlarmIndGreaterThanOrEqualTo(Short value) {
            addCriterion("FIRE_ALARM_IND >=", value, "fireAlarmInd");
            return (Criteria) this;
        }

        public Criteria andFireAlarmIndLessThan(Short value) {
            addCriterion("FIRE_ALARM_IND <", value, "fireAlarmInd");
            return (Criteria) this;
        }

        public Criteria andFireAlarmIndLessThanOrEqualTo(Short value) {
            addCriterion("FIRE_ALARM_IND <=", value, "fireAlarmInd");
            return (Criteria) this;
        }

        public Criteria andFireAlarmIndIn(List<Short> values) {
            addCriterion("FIRE_ALARM_IND in", values, "fireAlarmInd");
            return (Criteria) this;
        }

        public Criteria andFireAlarmIndNotIn(List<Short> values) {
            addCriterion("FIRE_ALARM_IND not in", values, "fireAlarmInd");
            return (Criteria) this;
        }

        public Criteria andFireAlarmIndBetween(Short value1, Short value2) {
            addCriterion("FIRE_ALARM_IND between", value1, value2, "fireAlarmInd");
            return (Criteria) this;
        }

        public Criteria andFireAlarmIndNotBetween(Short value1, Short value2) {
            addCriterion("FIRE_ALARM_IND not between", value1, value2, "fireAlarmInd");
            return (Criteria) this;
        }

        public Criteria andCraneFaultIsNull() {
            addCriterion("CRANE_FAULT is null");
            return (Criteria) this;
        }

        public Criteria andCraneFaultIsNotNull() {
            addCriterion("CRANE_FAULT is not null");
            return (Criteria) this;
        }

        public Criteria andCraneFaultEqualTo(Short value) {
            addCriterion("CRANE_FAULT =", value, "craneFault");
            return (Criteria) this;
        }

        public Criteria andCraneFaultNotEqualTo(Short value) {
            addCriterion("CRANE_FAULT <>", value, "craneFault");
            return (Criteria) this;
        }

        public Criteria andCraneFaultGreaterThan(Short value) {
            addCriterion("CRANE_FAULT >", value, "craneFault");
            return (Criteria) this;
        }

        public Criteria andCraneFaultGreaterThanOrEqualTo(Short value) {
            addCriterion("CRANE_FAULT >=", value, "craneFault");
            return (Criteria) this;
        }

        public Criteria andCraneFaultLessThan(Short value) {
            addCriterion("CRANE_FAULT <", value, "craneFault");
            return (Criteria) this;
        }

        public Criteria andCraneFaultLessThanOrEqualTo(Short value) {
            addCriterion("CRANE_FAULT <=", value, "craneFault");
            return (Criteria) this;
        }

        public Criteria andCraneFaultIn(List<Short> values) {
            addCriterion("CRANE_FAULT in", values, "craneFault");
            return (Criteria) this;
        }

        public Criteria andCraneFaultNotIn(List<Short> values) {
            addCriterion("CRANE_FAULT not in", values, "craneFault");
            return (Criteria) this;
        }

        public Criteria andCraneFaultBetween(Short value1, Short value2) {
            addCriterion("CRANE_FAULT between", value1, value2, "craneFault");
            return (Criteria) this;
        }

        public Criteria andCraneFaultNotBetween(Short value1, Short value2) {
            addCriterion("CRANE_FAULT not between", value1, value2, "craneFault");
            return (Criteria) this;
        }

        public Criteria andWindSpeedIndIsNull() {
            addCriterion("WIND_SPEED_IND is null");
            return (Criteria) this;
        }

        public Criteria andWindSpeedIndIsNotNull() {
            addCriterion("WIND_SPEED_IND is not null");
            return (Criteria) this;
        }

        public Criteria andWindSpeedIndEqualTo(Short value) {
            addCriterion("WIND_SPEED_IND =", value, "windSpeedInd");
            return (Criteria) this;
        }

        public Criteria andWindSpeedIndNotEqualTo(Short value) {
            addCriterion("WIND_SPEED_IND <>", value, "windSpeedInd");
            return (Criteria) this;
        }

        public Criteria andWindSpeedIndGreaterThan(Short value) {
            addCriterion("WIND_SPEED_IND >", value, "windSpeedInd");
            return (Criteria) this;
        }

        public Criteria andWindSpeedIndGreaterThanOrEqualTo(Short value) {
            addCriterion("WIND_SPEED_IND >=", value, "windSpeedInd");
            return (Criteria) this;
        }

        public Criteria andWindSpeedIndLessThan(Short value) {
            addCriterion("WIND_SPEED_IND <", value, "windSpeedInd");
            return (Criteria) this;
        }

        public Criteria andWindSpeedIndLessThanOrEqualTo(Short value) {
            addCriterion("WIND_SPEED_IND <=", value, "windSpeedInd");
            return (Criteria) this;
        }

        public Criteria andWindSpeedIndIn(List<Short> values) {
            addCriterion("WIND_SPEED_IND in", values, "windSpeedInd");
            return (Criteria) this;
        }

        public Criteria andWindSpeedIndNotIn(List<Short> values) {
            addCriterion("WIND_SPEED_IND not in", values, "windSpeedInd");
            return (Criteria) this;
        }

        public Criteria andWindSpeedIndBetween(Short value1, Short value2) {
            addCriterion("WIND_SPEED_IND between", value1, value2, "windSpeedInd");
            return (Criteria) this;
        }

        public Criteria andWindSpeedIndNotBetween(Short value1, Short value2) {
            addCriterion("WIND_SPEED_IND not between", value1, value2, "windSpeedInd");
            return (Criteria) this;
        }

        public Criteria andSpreaderSizeIsNull() {
            addCriterion("SPREADER_SIZE is null");
            return (Criteria) this;
        }

        public Criteria andSpreaderSizeIsNotNull() {
            addCriterion("SPREADER_SIZE is not null");
            return (Criteria) this;
        }

        public Criteria andSpreaderSizeEqualTo(Short value) {
            addCriterion("SPREADER_SIZE =", value, "spreaderSize");
            return (Criteria) this;
        }

        public Criteria andSpreaderSizeNotEqualTo(Short value) {
            addCriterion("SPREADER_SIZE <>", value, "spreaderSize");
            return (Criteria) this;
        }

        public Criteria andSpreaderSizeGreaterThan(Short value) {
            addCriterion("SPREADER_SIZE >", value, "spreaderSize");
            return (Criteria) this;
        }

        public Criteria andSpreaderSizeGreaterThanOrEqualTo(Short value) {
            addCriterion("SPREADER_SIZE >=", value, "spreaderSize");
            return (Criteria) this;
        }

        public Criteria andSpreaderSizeLessThan(Short value) {
            addCriterion("SPREADER_SIZE <", value, "spreaderSize");
            return (Criteria) this;
        }

        public Criteria andSpreaderSizeLessThanOrEqualTo(Short value) {
            addCriterion("SPREADER_SIZE <=", value, "spreaderSize");
            return (Criteria) this;
        }

        public Criteria andSpreaderSizeIn(List<Short> values) {
            addCriterion("SPREADER_SIZE in", values, "spreaderSize");
            return (Criteria) this;
        }

        public Criteria andSpreaderSizeNotIn(List<Short> values) {
            addCriterion("SPREADER_SIZE not in", values, "spreaderSize");
            return (Criteria) this;
        }

        public Criteria andSpreaderSizeBetween(Short value1, Short value2) {
            addCriterion("SPREADER_SIZE between", value1, value2, "spreaderSize");
            return (Criteria) this;
        }

        public Criteria andSpreaderSizeNotBetween(Short value1, Short value2) {
            addCriterion("SPREADER_SIZE not between", value1, value2, "spreaderSize");
            return (Criteria) this;
        }

        public Criteria andTwistLockIsNull() {
            addCriterion("TWIST_LOCK is null");
            return (Criteria) this;
        }

        public Criteria andTwistLockIsNotNull() {
            addCriterion("TWIST_LOCK is not null");
            return (Criteria) this;
        }

        public Criteria andTwistLockEqualTo(Short value) {
            addCriterion("TWIST_LOCK =", value, "twistLock");
            return (Criteria) this;
        }

        public Criteria andTwistLockNotEqualTo(Short value) {
            addCriterion("TWIST_LOCK <>", value, "twistLock");
            return (Criteria) this;
        }

        public Criteria andTwistLockGreaterThan(Short value) {
            addCriterion("TWIST_LOCK >", value, "twistLock");
            return (Criteria) this;
        }

        public Criteria andTwistLockGreaterThanOrEqualTo(Short value) {
            addCriterion("TWIST_LOCK >=", value, "twistLock");
            return (Criteria) this;
        }

        public Criteria andTwistLockLessThan(Short value) {
            addCriterion("TWIST_LOCK <", value, "twistLock");
            return (Criteria) this;
        }

        public Criteria andTwistLockLessThanOrEqualTo(Short value) {
            addCriterion("TWIST_LOCK <=", value, "twistLock");
            return (Criteria) this;
        }

        public Criteria andTwistLockIn(List<Short> values) {
            addCriterion("TWIST_LOCK in", values, "twistLock");
            return (Criteria) this;
        }

        public Criteria andTwistLockNotIn(List<Short> values) {
            addCriterion("TWIST_LOCK not in", values, "twistLock");
            return (Criteria) this;
        }

        public Criteria andTwistLockBetween(Short value1, Short value2) {
            addCriterion("TWIST_LOCK between", value1, value2, "twistLock");
            return (Criteria) this;
        }

        public Criteria andTwistLockNotBetween(Short value1, Short value2) {
            addCriterion("TWIST_LOCK not between", value1, value2, "twistLock");
            return (Criteria) this;
        }

        public Criteria andLandedIsNull() {
            addCriterion("LANDED is null");
            return (Criteria) this;
        }

        public Criteria andLandedIsNotNull() {
            addCriterion("LANDED is not null");
            return (Criteria) this;
        }

        public Criteria andLandedEqualTo(Short value) {
            addCriterion("LANDED =", value, "landed");
            return (Criteria) this;
        }

        public Criteria andLandedNotEqualTo(Short value) {
            addCriterion("LANDED <>", value, "landed");
            return (Criteria) this;
        }

        public Criteria andLandedGreaterThan(Short value) {
            addCriterion("LANDED >", value, "landed");
            return (Criteria) this;
        }

        public Criteria andLandedGreaterThanOrEqualTo(Short value) {
            addCriterion("LANDED >=", value, "landed");
            return (Criteria) this;
        }

        public Criteria andLandedLessThan(Short value) {
            addCriterion("LANDED <", value, "landed");
            return (Criteria) this;
        }

        public Criteria andLandedLessThanOrEqualTo(Short value) {
            addCriterion("LANDED <=", value, "landed");
            return (Criteria) this;
        }

        public Criteria andLandedIn(List<Short> values) {
            addCriterion("LANDED in", values, "landed");
            return (Criteria) this;
        }

        public Criteria andLandedNotIn(List<Short> values) {
            addCriterion("LANDED not in", values, "landed");
            return (Criteria) this;
        }

        public Criteria andLandedBetween(Short value1, Short value2) {
            addCriterion("LANDED between", value1, value2, "landed");
            return (Criteria) this;
        }

        public Criteria andLandedNotBetween(Short value1, Short value2) {
            addCriterion("LANDED not between", value1, value2, "landed");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("WEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("WEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(Integer value) {
            addCriterion("WEIGHT =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(Integer value) {
            addCriterion("WEIGHT <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(Integer value) {
            addCriterion("WEIGHT >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("WEIGHT >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(Integer value) {
            addCriterion("WEIGHT <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(Integer value) {
            addCriterion("WEIGHT <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<Integer> values) {
            addCriterion("WEIGHT in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<Integer> values) {
            addCriterion("WEIGHT not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(Integer value1, Integer value2) {
            addCriterion("WEIGHT between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("WEIGHT not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andActualBlockIsNull() {
            addCriterion("ACTUAL_BLOCK is null");
            return (Criteria) this;
        }

        public Criteria andActualBlockIsNotNull() {
            addCriterion("ACTUAL_BLOCK is not null");
            return (Criteria) this;
        }

        public Criteria andActualBlockEqualTo(String value) {
            addCriterion("ACTUAL_BLOCK =", value, "actualBlock");
            return (Criteria) this;
        }

        public Criteria andActualBlockNotEqualTo(String value) {
            addCriterion("ACTUAL_BLOCK <>", value, "actualBlock");
            return (Criteria) this;
        }

        public Criteria andActualBlockGreaterThan(String value) {
            addCriterion("ACTUAL_BLOCK >", value, "actualBlock");
            return (Criteria) this;
        }

        public Criteria andActualBlockGreaterThanOrEqualTo(String value) {
            addCriterion("ACTUAL_BLOCK >=", value, "actualBlock");
            return (Criteria) this;
        }

        public Criteria andActualBlockLessThan(String value) {
            addCriterion("ACTUAL_BLOCK <", value, "actualBlock");
            return (Criteria) this;
        }

        public Criteria andActualBlockLessThanOrEqualTo(String value) {
            addCriterion("ACTUAL_BLOCK <=", value, "actualBlock");
            return (Criteria) this;
        }

        public Criteria andActualBlockLike(String value) {
            addCriterion("ACTUAL_BLOCK like", value, "actualBlock");
            return (Criteria) this;
        }

        public Criteria andActualBlockNotLike(String value) {
            addCriterion("ACTUAL_BLOCK not like", value, "actualBlock");
            return (Criteria) this;
        }

        public Criteria andActualBlockIn(List<String> values) {
            addCriterion("ACTUAL_BLOCK in", values, "actualBlock");
            return (Criteria) this;
        }

        public Criteria andActualBlockNotIn(List<String> values) {
            addCriterion("ACTUAL_BLOCK not in", values, "actualBlock");
            return (Criteria) this;
        }

        public Criteria andActualBlockBetween(String value1, String value2) {
            addCriterion("ACTUAL_BLOCK between", value1, value2, "actualBlock");
            return (Criteria) this;
        }

        public Criteria andActualBlockNotBetween(String value1, String value2) {
            addCriterion("ACTUAL_BLOCK not between", value1, value2, "actualBlock");
            return (Criteria) this;
        }

        public Criteria andActualBayIsNull() {
            addCriterion("ACTUAL_BAY is null");
            return (Criteria) this;
        }

        public Criteria andActualBayIsNotNull() {
            addCriterion("ACTUAL_BAY is not null");
            return (Criteria) this;
        }

        public Criteria andActualBayEqualTo(Short value) {
            addCriterion("ACTUAL_BAY =", value, "actualBay");
            return (Criteria) this;
        }

        public Criteria andActualBayNotEqualTo(Short value) {
            addCriterion("ACTUAL_BAY <>", value, "actualBay");
            return (Criteria) this;
        }

        public Criteria andActualBayGreaterThan(Short value) {
            addCriterion("ACTUAL_BAY >", value, "actualBay");
            return (Criteria) this;
        }

        public Criteria andActualBayGreaterThanOrEqualTo(Short value) {
            addCriterion("ACTUAL_BAY >=", value, "actualBay");
            return (Criteria) this;
        }

        public Criteria andActualBayLessThan(Short value) {
            addCriterion("ACTUAL_BAY <", value, "actualBay");
            return (Criteria) this;
        }

        public Criteria andActualBayLessThanOrEqualTo(Short value) {
            addCriterion("ACTUAL_BAY <=", value, "actualBay");
            return (Criteria) this;
        }

        public Criteria andActualBayIn(List<Short> values) {
            addCriterion("ACTUAL_BAY in", values, "actualBay");
            return (Criteria) this;
        }

        public Criteria andActualBayNotIn(List<Short> values) {
            addCriterion("ACTUAL_BAY not in", values, "actualBay");
            return (Criteria) this;
        }

        public Criteria andActualBayBetween(Short value1, Short value2) {
            addCriterion("ACTUAL_BAY between", value1, value2, "actualBay");
            return (Criteria) this;
        }

        public Criteria andActualBayNotBetween(Short value1, Short value2) {
            addCriterion("ACTUAL_BAY not between", value1, value2, "actualBay");
            return (Criteria) this;
        }

        public Criteria andActualRowIsNull() {
            addCriterion("ACTUAL_ROW is null");
            return (Criteria) this;
        }

        public Criteria andActualRowIsNotNull() {
            addCriterion("ACTUAL_ROW is not null");
            return (Criteria) this;
        }

        public Criteria andActualRowEqualTo(Short value) {
            addCriterion("ACTUAL_ROW =", value, "actualRow");
            return (Criteria) this;
        }

        public Criteria andActualRowNotEqualTo(Short value) {
            addCriterion("ACTUAL_ROW <>", value, "actualRow");
            return (Criteria) this;
        }

        public Criteria andActualRowGreaterThan(Short value) {
            addCriterion("ACTUAL_ROW >", value, "actualRow");
            return (Criteria) this;
        }

        public Criteria andActualRowGreaterThanOrEqualTo(Short value) {
            addCriterion("ACTUAL_ROW >=", value, "actualRow");
            return (Criteria) this;
        }

        public Criteria andActualRowLessThan(Short value) {
            addCriterion("ACTUAL_ROW <", value, "actualRow");
            return (Criteria) this;
        }

        public Criteria andActualRowLessThanOrEqualTo(Short value) {
            addCriterion("ACTUAL_ROW <=", value, "actualRow");
            return (Criteria) this;
        }

        public Criteria andActualRowIn(List<Short> values) {
            addCriterion("ACTUAL_ROW in", values, "actualRow");
            return (Criteria) this;
        }

        public Criteria andActualRowNotIn(List<Short> values) {
            addCriterion("ACTUAL_ROW not in", values, "actualRow");
            return (Criteria) this;
        }

        public Criteria andActualRowBetween(Short value1, Short value2) {
            addCriterion("ACTUAL_ROW between", value1, value2, "actualRow");
            return (Criteria) this;
        }

        public Criteria andActualRowNotBetween(Short value1, Short value2) {
            addCriterion("ACTUAL_ROW not between", value1, value2, "actualRow");
            return (Criteria) this;
        }

        public Criteria andActualHeightIsNull() {
            addCriterion("ACTUAL_HEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andActualHeightIsNotNull() {
            addCriterion("ACTUAL_HEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andActualHeightEqualTo(Integer value) {
            addCriterion("ACTUAL_HEIGHT =", value, "actualHeight");
            return (Criteria) this;
        }

        public Criteria andActualHeightNotEqualTo(Integer value) {
            addCriterion("ACTUAL_HEIGHT <>", value, "actualHeight");
            return (Criteria) this;
        }

        public Criteria andActualHeightGreaterThan(Integer value) {
            addCriterion("ACTUAL_HEIGHT >", value, "actualHeight");
            return (Criteria) this;
        }

        public Criteria andActualHeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACTUAL_HEIGHT >=", value, "actualHeight");
            return (Criteria) this;
        }

        public Criteria andActualHeightLessThan(Integer value) {
            addCriterion("ACTUAL_HEIGHT <", value, "actualHeight");
            return (Criteria) this;
        }

        public Criteria andActualHeightLessThanOrEqualTo(Integer value) {
            addCriterion("ACTUAL_HEIGHT <=", value, "actualHeight");
            return (Criteria) this;
        }

        public Criteria andActualHeightIn(List<Integer> values) {
            addCriterion("ACTUAL_HEIGHT in", values, "actualHeight");
            return (Criteria) this;
        }

        public Criteria andActualHeightNotIn(List<Integer> values) {
            addCriterion("ACTUAL_HEIGHT not in", values, "actualHeight");
            return (Criteria) this;
        }

        public Criteria andActualHeightBetween(Integer value1, Integer value2) {
            addCriterion("ACTUAL_HEIGHT between", value1, value2, "actualHeight");
            return (Criteria) this;
        }

        public Criteria andActualHeightNotBetween(Integer value1, Integer value2) {
            addCriterion("ACTUAL_HEIGHT not between", value1, value2, "actualHeight");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsIsNull() {
            addCriterion("JOB_ORDER_SEQ_MS is null");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsIsNotNull() {
            addCriterion("JOB_ORDER_SEQ_MS is not null");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsEqualTo(Long value) {
            addCriterion("JOB_ORDER_SEQ_MS =", value, "jobOrderSeqMs");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsNotEqualTo(Long value) {
            addCriterion("JOB_ORDER_SEQ_MS <>", value, "jobOrderSeqMs");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsGreaterThan(Long value) {
            addCriterion("JOB_ORDER_SEQ_MS >", value, "jobOrderSeqMs");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsGreaterThanOrEqualTo(Long value) {
            addCriterion("JOB_ORDER_SEQ_MS >=", value, "jobOrderSeqMs");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsLessThan(Long value) {
            addCriterion("JOB_ORDER_SEQ_MS <", value, "jobOrderSeqMs");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsLessThanOrEqualTo(Long value) {
            addCriterion("JOB_ORDER_SEQ_MS <=", value, "jobOrderSeqMs");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsIn(List<Long> values) {
            addCriterion("JOB_ORDER_SEQ_MS in", values, "jobOrderSeqMs");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsNotIn(List<Long> values) {
            addCriterion("JOB_ORDER_SEQ_MS not in", values, "jobOrderSeqMs");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsBetween(Long value1, Long value2) {
            addCriterion("JOB_ORDER_SEQ_MS between", value1, value2, "jobOrderSeqMs");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsNotBetween(Long value1, Long value2) {
            addCriterion("JOB_ORDER_SEQ_MS not between", value1, value2, "jobOrderSeqMs");
            return (Criteria) this;
        }

        public Criteria andConnectStatusIsNull() {
            addCriterion("CONNECT_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andConnectStatusIsNotNull() {
            addCriterion("CONNECT_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andConnectStatusEqualTo(Short value) {
            addCriterion("CONNECT_STATUS =", value, "connectStatus");
            return (Criteria) this;
        }

        public Criteria andConnectStatusNotEqualTo(Short value) {
            addCriterion("CONNECT_STATUS <>", value, "connectStatus");
            return (Criteria) this;
        }

        public Criteria andConnectStatusGreaterThan(Short value) {
            addCriterion("CONNECT_STATUS >", value, "connectStatus");
            return (Criteria) this;
        }

        public Criteria andConnectStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("CONNECT_STATUS >=", value, "connectStatus");
            return (Criteria) this;
        }

        public Criteria andConnectStatusLessThan(Short value) {
            addCriterion("CONNECT_STATUS <", value, "connectStatus");
            return (Criteria) this;
        }

        public Criteria andConnectStatusLessThanOrEqualTo(Short value) {
            addCriterion("CONNECT_STATUS <=", value, "connectStatus");
            return (Criteria) this;
        }

        public Criteria andConnectStatusIn(List<Short> values) {
            addCriterion("CONNECT_STATUS in", values, "connectStatus");
            return (Criteria) this;
        }

        public Criteria andConnectStatusNotIn(List<Short> values) {
            addCriterion("CONNECT_STATUS not in", values, "connectStatus");
            return (Criteria) this;
        }

        public Criteria andConnectStatusBetween(Short value1, Short value2) {
            addCriterion("CONNECT_STATUS between", value1, value2, "connectStatus");
            return (Criteria) this;
        }

        public Criteria andConnectStatusNotBetween(Short value1, Short value2) {
            addCriterion("CONNECT_STATUS not between", value1, value2, "connectStatus");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("MODIFY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("MODIFY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("MODIFY_TIME =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("MODIFY_TIME <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("MODIFY_TIME >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("MODIFY_TIME <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("MODIFY_TIME in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("MODIFY_TIME not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtIsNull() {
            addCriterion("JOB_ORDER_SEQ_DT is null");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtIsNotNull() {
            addCriterion("JOB_ORDER_SEQ_DT is not null");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtEqualTo(Short value) {
            addCriterion("JOB_ORDER_SEQ_DT =", value, "jobOrderSeqDt");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtNotEqualTo(Short value) {
            addCriterion("JOB_ORDER_SEQ_DT <>", value, "jobOrderSeqDt");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtGreaterThan(Short value) {
            addCriterion("JOB_ORDER_SEQ_DT >", value, "jobOrderSeqDt");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtGreaterThanOrEqualTo(Short value) {
            addCriterion("JOB_ORDER_SEQ_DT >=", value, "jobOrderSeqDt");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtLessThan(Short value) {
            addCriterion("JOB_ORDER_SEQ_DT <", value, "jobOrderSeqDt");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtLessThanOrEqualTo(Short value) {
            addCriterion("JOB_ORDER_SEQ_DT <=", value, "jobOrderSeqDt");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtIn(List<Short> values) {
            addCriterion("JOB_ORDER_SEQ_DT in", values, "jobOrderSeqDt");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtNotIn(List<Short> values) {
            addCriterion("JOB_ORDER_SEQ_DT not in", values, "jobOrderSeqDt");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtBetween(Short value1, Short value2) {
            addCriterion("JOB_ORDER_SEQ_DT between", value1, value2, "jobOrderSeqDt");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtNotBetween(Short value1, Short value2) {
            addCriterion("JOB_ORDER_SEQ_DT not between", value1, value2, "jobOrderSeqDt");
            return (Criteria) this;
        }

        public Criteria andCommandSeqIsNull() {
            addCriterion("COMMAND_SEQ is null");
            return (Criteria) this;
        }

        public Criteria andCommandSeqIsNotNull() {
            addCriterion("COMMAND_SEQ is not null");
            return (Criteria) this;
        }

        public Criteria andCommandSeqEqualTo(Long value) {
            addCriterion("COMMAND_SEQ =", value, "commandSeq");
            return (Criteria) this;
        }

        public Criteria andCommandSeqNotEqualTo(Long value) {
            addCriterion("COMMAND_SEQ <>", value, "commandSeq");
            return (Criteria) this;
        }

        public Criteria andCommandSeqGreaterThan(Long value) {
            addCriterion("COMMAND_SEQ >", value, "commandSeq");
            return (Criteria) this;
        }

        public Criteria andCommandSeqGreaterThanOrEqualTo(Long value) {
            addCriterion("COMMAND_SEQ >=", value, "commandSeq");
            return (Criteria) this;
        }

        public Criteria andCommandSeqLessThan(Long value) {
            addCriterion("COMMAND_SEQ <", value, "commandSeq");
            return (Criteria) this;
        }

        public Criteria andCommandSeqLessThanOrEqualTo(Long value) {
            addCriterion("COMMAND_SEQ <=", value, "commandSeq");
            return (Criteria) this;
        }

        public Criteria andCommandSeqIn(List<Long> values) {
            addCriterion("COMMAND_SEQ in", values, "commandSeq");
            return (Criteria) this;
        }

        public Criteria andCommandSeqNotIn(List<Long> values) {
            addCriterion("COMMAND_SEQ not in", values, "commandSeq");
            return (Criteria) this;
        }

        public Criteria andCommandSeqBetween(Long value1, Long value2) {
            addCriterion("COMMAND_SEQ between", value1, value2, "commandSeq");
            return (Criteria) this;
        }

        public Criteria andCommandSeqNotBetween(Long value1, Long value2) {
            addCriterion("COMMAND_SEQ not between", value1, value2, "commandSeq");
            return (Criteria) this;
        }

        public Criteria andEnableOnIsNull() {
            addCriterion("ENABLE_ON is null");
            return (Criteria) this;
        }

        public Criteria andEnableOnIsNotNull() {
            addCriterion("ENABLE_ON is not null");
            return (Criteria) this;
        }

        public Criteria andEnableOnEqualTo(Short value) {
            addCriterion("ENABLE_ON =", value, "enableOn");
            return (Criteria) this;
        }

        public Criteria andEnableOnNotEqualTo(Short value) {
            addCriterion("ENABLE_ON <>", value, "enableOn");
            return (Criteria) this;
        }

        public Criteria andEnableOnGreaterThan(Short value) {
            addCriterion("ENABLE_ON >", value, "enableOn");
            return (Criteria) this;
        }

        public Criteria andEnableOnGreaterThanOrEqualTo(Short value) {
            addCriterion("ENABLE_ON >=", value, "enableOn");
            return (Criteria) this;
        }

        public Criteria andEnableOnLessThan(Short value) {
            addCriterion("ENABLE_ON <", value, "enableOn");
            return (Criteria) this;
        }

        public Criteria andEnableOnLessThanOrEqualTo(Short value) {
            addCriterion("ENABLE_ON <=", value, "enableOn");
            return (Criteria) this;
        }

        public Criteria andEnableOnIn(List<Short> values) {
            addCriterion("ENABLE_ON in", values, "enableOn");
            return (Criteria) this;
        }

        public Criteria andEnableOnNotIn(List<Short> values) {
            addCriterion("ENABLE_ON not in", values, "enableOn");
            return (Criteria) this;
        }

        public Criteria andEnableOnBetween(Short value1, Short value2) {
            addCriterion("ENABLE_ON between", value1, value2, "enableOn");
            return (Criteria) this;
        }

        public Criteria andEnableOnNotBetween(Short value1, Short value2) {
            addCriterion("ENABLE_ON not between", value1, value2, "enableOn");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ARMGSTATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}