package com.example.dao.entity;

public class ArmgslottosKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTTOS.BLOCK_NO
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    private String blockNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTTOS.BAY_NO
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    private Short bayNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTTOS.ROW_NO
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    private Short rowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTTOS.TIER_NO
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    private Short tierNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTTOS.BLOCK_NO
     *
     * @return the value of ARMGSLOTTOS.BLOCK_NO
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public String getBlockNo() {
        return blockNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTTOS.BLOCK_NO
     *
     * @param blockNo the value for ARMGSLOTTOS.BLOCK_NO
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public void setBlockNo(String blockNo) {
        this.blockNo = blockNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTTOS.BAY_NO
     *
     * @return the value of ARMGSLOTTOS.BAY_NO
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public Short getBayNo() {
        return bayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTTOS.BAY_NO
     *
     * @param bayNo the value for ARMGSLOTTOS.BAY_NO
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public void setBayNo(Short bayNo) {
        this.bayNo = bayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTTOS.ROW_NO
     *
     * @return the value of ARMGSLOTTOS.ROW_NO
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public Short getRowNo() {
        return rowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTTOS.ROW_NO
     *
     * @param rowNo the value for ARMGSLOTTOS.ROW_NO
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public void setRowNo(Short rowNo) {
        this.rowNo = rowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTTOS.TIER_NO
     *
     * @return the value of ARMGSLOTTOS.TIER_NO
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public Short getTierNo() {
        return tierNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTTOS.TIER_NO
     *
     * @param tierNo the value for ARMGSLOTTOS.TIER_NO
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public void setTierNo(Short tierNo) {
        this.tierNo = tierNo;
    }
}