package com.example.dao.entity;

import java.util.Date;

public class Armgstatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.ARMG_ID
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private String armgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.MAN_INTERVEN
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Short manInterven;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.WAITING_TYPE
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Short waitingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.OPERATION_MODE
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Short operationMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.AUTO_STATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Short autoStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.CONSOLE_CONNECTED
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Integer consoleConnected;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.CRANE_ON
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Short craneOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.LIGHT_ON
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Short lightOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.MAX_SPEED
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Short maxSpeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.RAMP_RATE
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Short rampRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.TPS_FOG_MODE
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Short tpsFogMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.FIRE_ALARM_IND
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Short fireAlarmInd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.CRANE_FAULT
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Short craneFault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.WIND_SPEED_IND
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Short windSpeedInd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.SPREADER_SIZE
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Short spreaderSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.TWIST_LOCK
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Short twistLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.LANDED
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Short landed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.WEIGHT
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.ACTUAL_BLOCK
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private String actualBlock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.ACTUAL_BAY
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Short actualBay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.ACTUAL_ROW
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Short actualRow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.ACTUAL_HEIGHT
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Integer actualHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.JOB_ORDER_SEQ_MS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Long jobOrderSeqMs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.CONNECT_STATUS
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Short connectStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.MODIFY_TIME
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.JOB_ORDER_SEQ_DT
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Short jobOrderSeqDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.COMMAND_SEQ
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Long commandSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSTATUS.ENABLE_ON
     *
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    private Short enableOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.ARMG_ID
     *
     * @return the value of ARMGSTATUS.ARMG_ID
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public String getArmgId() {
        return armgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.ARMG_ID
     *
     * @param armgId the value for ARMGSTATUS.ARMG_ID
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setArmgId(String armgId) {
        this.armgId = armgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.MAN_INTERVEN
     *
     * @return the value of ARMGSTATUS.MAN_INTERVEN
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Short getManInterven() {
        return manInterven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.MAN_INTERVEN
     *
     * @param manInterven the value for ARMGSTATUS.MAN_INTERVEN
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setManInterven(Short manInterven) {
        this.manInterven = manInterven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.WAITING_TYPE
     *
     * @return the value of ARMGSTATUS.WAITING_TYPE
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Short getWaitingType() {
        return waitingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.WAITING_TYPE
     *
     * @param waitingType the value for ARMGSTATUS.WAITING_TYPE
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setWaitingType(Short waitingType) {
        this.waitingType = waitingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.OPERATION_MODE
     *
     * @return the value of ARMGSTATUS.OPERATION_MODE
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Short getOperationMode() {
        return operationMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.OPERATION_MODE
     *
     * @param operationMode the value for ARMGSTATUS.OPERATION_MODE
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setOperationMode(Short operationMode) {
        this.operationMode = operationMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.AUTO_STATUS
     *
     * @return the value of ARMGSTATUS.AUTO_STATUS
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Short getAutoStatus() {
        return autoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.AUTO_STATUS
     *
     * @param autoStatus the value for ARMGSTATUS.AUTO_STATUS
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setAutoStatus(Short autoStatus) {
        this.autoStatus = autoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.CONSOLE_CONNECTED
     *
     * @return the value of ARMGSTATUS.CONSOLE_CONNECTED
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Integer getConsoleConnected() {
        return consoleConnected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.CONSOLE_CONNECTED
     *
     * @param consoleConnected the value for ARMGSTATUS.CONSOLE_CONNECTED
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setConsoleConnected(Integer consoleConnected) {
        this.consoleConnected = consoleConnected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.CRANE_ON
     *
     * @return the value of ARMGSTATUS.CRANE_ON
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Short getCraneOn() {
        return craneOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.CRANE_ON
     *
     * @param craneOn the value for ARMGSTATUS.CRANE_ON
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setCraneOn(Short craneOn) {
        this.craneOn = craneOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.LIGHT_ON
     *
     * @return the value of ARMGSTATUS.LIGHT_ON
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Short getLightOn() {
        return lightOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.LIGHT_ON
     *
     * @param lightOn the value for ARMGSTATUS.LIGHT_ON
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setLightOn(Short lightOn) {
        this.lightOn = lightOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.MAX_SPEED
     *
     * @return the value of ARMGSTATUS.MAX_SPEED
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Short getMaxSpeed() {
        return maxSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.MAX_SPEED
     *
     * @param maxSpeed the value for ARMGSTATUS.MAX_SPEED
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setMaxSpeed(Short maxSpeed) {
        this.maxSpeed = maxSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.RAMP_RATE
     *
     * @return the value of ARMGSTATUS.RAMP_RATE
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Short getRampRate() {
        return rampRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.RAMP_RATE
     *
     * @param rampRate the value for ARMGSTATUS.RAMP_RATE
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setRampRate(Short rampRate) {
        this.rampRate = rampRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.TPS_FOG_MODE
     *
     * @return the value of ARMGSTATUS.TPS_FOG_MODE
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Short getTpsFogMode() {
        return tpsFogMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.TPS_FOG_MODE
     *
     * @param tpsFogMode the value for ARMGSTATUS.TPS_FOG_MODE
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setTpsFogMode(Short tpsFogMode) {
        this.tpsFogMode = tpsFogMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.FIRE_ALARM_IND
     *
     * @return the value of ARMGSTATUS.FIRE_ALARM_IND
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Short getFireAlarmInd() {
        return fireAlarmInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.FIRE_ALARM_IND
     *
     * @param fireAlarmInd the value for ARMGSTATUS.FIRE_ALARM_IND
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setFireAlarmInd(Short fireAlarmInd) {
        this.fireAlarmInd = fireAlarmInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.CRANE_FAULT
     *
     * @return the value of ARMGSTATUS.CRANE_FAULT
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Short getCraneFault() {
        return craneFault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.CRANE_FAULT
     *
     * @param craneFault the value for ARMGSTATUS.CRANE_FAULT
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setCraneFault(Short craneFault) {
        this.craneFault = craneFault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.WIND_SPEED_IND
     *
     * @return the value of ARMGSTATUS.WIND_SPEED_IND
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Short getWindSpeedInd() {
        return windSpeedInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.WIND_SPEED_IND
     *
     * @param windSpeedInd the value for ARMGSTATUS.WIND_SPEED_IND
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setWindSpeedInd(Short windSpeedInd) {
        this.windSpeedInd = windSpeedInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.SPREADER_SIZE
     *
     * @return the value of ARMGSTATUS.SPREADER_SIZE
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Short getSpreaderSize() {
        return spreaderSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.SPREADER_SIZE
     *
     * @param spreaderSize the value for ARMGSTATUS.SPREADER_SIZE
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setSpreaderSize(Short spreaderSize) {
        this.spreaderSize = spreaderSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.TWIST_LOCK
     *
     * @return the value of ARMGSTATUS.TWIST_LOCK
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Short getTwistLock() {
        return twistLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.TWIST_LOCK
     *
     * @param twistLock the value for ARMGSTATUS.TWIST_LOCK
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setTwistLock(Short twistLock) {
        this.twistLock = twistLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.LANDED
     *
     * @return the value of ARMGSTATUS.LANDED
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Short getLanded() {
        return landed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.LANDED
     *
     * @param landed the value for ARMGSTATUS.LANDED
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setLanded(Short landed) {
        this.landed = landed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.WEIGHT
     *
     * @return the value of ARMGSTATUS.WEIGHT
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.WEIGHT
     *
     * @param weight the value for ARMGSTATUS.WEIGHT
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.ACTUAL_BLOCK
     *
     * @return the value of ARMGSTATUS.ACTUAL_BLOCK
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public String getActualBlock() {
        return actualBlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.ACTUAL_BLOCK
     *
     * @param actualBlock the value for ARMGSTATUS.ACTUAL_BLOCK
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setActualBlock(String actualBlock) {
        this.actualBlock = actualBlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.ACTUAL_BAY
     *
     * @return the value of ARMGSTATUS.ACTUAL_BAY
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Short getActualBay() {
        return actualBay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.ACTUAL_BAY
     *
     * @param actualBay the value for ARMGSTATUS.ACTUAL_BAY
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setActualBay(Short actualBay) {
        this.actualBay = actualBay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.ACTUAL_ROW
     *
     * @return the value of ARMGSTATUS.ACTUAL_ROW
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Short getActualRow() {
        return actualRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.ACTUAL_ROW
     *
     * @param actualRow the value for ARMGSTATUS.ACTUAL_ROW
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setActualRow(Short actualRow) {
        this.actualRow = actualRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.ACTUAL_HEIGHT
     *
     * @return the value of ARMGSTATUS.ACTUAL_HEIGHT
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Integer getActualHeight() {
        return actualHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.ACTUAL_HEIGHT
     *
     * @param actualHeight the value for ARMGSTATUS.ACTUAL_HEIGHT
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setActualHeight(Integer actualHeight) {
        this.actualHeight = actualHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.JOB_ORDER_SEQ_MS
     *
     * @return the value of ARMGSTATUS.JOB_ORDER_SEQ_MS
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Long getJobOrderSeqMs() {
        return jobOrderSeqMs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.JOB_ORDER_SEQ_MS
     *
     * @param jobOrderSeqMs the value for ARMGSTATUS.JOB_ORDER_SEQ_MS
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setJobOrderSeqMs(Long jobOrderSeqMs) {
        this.jobOrderSeqMs = jobOrderSeqMs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.CONNECT_STATUS
     *
     * @return the value of ARMGSTATUS.CONNECT_STATUS
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Short getConnectStatus() {
        return connectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.CONNECT_STATUS
     *
     * @param connectStatus the value for ARMGSTATUS.CONNECT_STATUS
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setConnectStatus(Short connectStatus) {
        this.connectStatus = connectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.MODIFY_TIME
     *
     * @return the value of ARMGSTATUS.MODIFY_TIME
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.MODIFY_TIME
     *
     * @param modifyTime the value for ARMGSTATUS.MODIFY_TIME
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.JOB_ORDER_SEQ_DT
     *
     * @return the value of ARMGSTATUS.JOB_ORDER_SEQ_DT
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Short getJobOrderSeqDt() {
        return jobOrderSeqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.JOB_ORDER_SEQ_DT
     *
     * @param jobOrderSeqDt the value for ARMGSTATUS.JOB_ORDER_SEQ_DT
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setJobOrderSeqDt(Short jobOrderSeqDt) {
        this.jobOrderSeqDt = jobOrderSeqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.COMMAND_SEQ
     *
     * @return the value of ARMGSTATUS.COMMAND_SEQ
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Long getCommandSeq() {
        return commandSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.COMMAND_SEQ
     *
     * @param commandSeq the value for ARMGSTATUS.COMMAND_SEQ
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setCommandSeq(Long commandSeq) {
        this.commandSeq = commandSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSTATUS.ENABLE_ON
     *
     * @return the value of ARMGSTATUS.ENABLE_ON
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public Short getEnableOn() {
        return enableOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSTATUS.ENABLE_ON
     *
     * @param enableOn the value for ARMGSTATUS.ENABLE_ON
     * @mbg.generated Mon Nov 12 11:48:44 GMT+08:00 2018
     */
    public void setEnableOn(Short enableOn) {
        this.enableOn = enableOn;
    }
}