package com.example.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ArmgslotxjdExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ARMGSLOTXJD
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ARMGSLOTXJD
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ARMGSLOTXJD
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTXJD
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public ArmgslotxjdExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTXJD
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTXJD
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTXJD
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTXJD
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTXJD
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTXJD
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTXJD
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTXJD
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTXJD
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGSLOTXJD
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ARMGSLOTXJD
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBlockNoIsNull() {
            addCriterion("BLOCK_NO is null");
            return (Criteria) this;
        }

        public Criteria andBlockNoIsNotNull() {
            addCriterion("BLOCK_NO is not null");
            return (Criteria) this;
        }

        public Criteria andBlockNoEqualTo(String value) {
            addCriterion("BLOCK_NO =", value, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoNotEqualTo(String value) {
            addCriterion("BLOCK_NO <>", value, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoGreaterThan(String value) {
            addCriterion("BLOCK_NO >", value, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoGreaterThanOrEqualTo(String value) {
            addCriterion("BLOCK_NO >=", value, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoLessThan(String value) {
            addCriterion("BLOCK_NO <", value, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoLessThanOrEqualTo(String value) {
            addCriterion("BLOCK_NO <=", value, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoLike(String value) {
            addCriterion("BLOCK_NO like", value, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoNotLike(String value) {
            addCriterion("BLOCK_NO not like", value, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoIn(List<String> values) {
            addCriterion("BLOCK_NO in", values, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoNotIn(List<String> values) {
            addCriterion("BLOCK_NO not in", values, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoBetween(String value1, String value2) {
            addCriterion("BLOCK_NO between", value1, value2, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoNotBetween(String value1, String value2) {
            addCriterion("BLOCK_NO not between", value1, value2, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBayNoIsNull() {
            addCriterion("BAY_NO is null");
            return (Criteria) this;
        }

        public Criteria andBayNoIsNotNull() {
            addCriterion("BAY_NO is not null");
            return (Criteria) this;
        }

        public Criteria andBayNoEqualTo(Short value) {
            addCriterion("BAY_NO =", value, "bayNo");
            return (Criteria) this;
        }

        public Criteria andBayNoNotEqualTo(Short value) {
            addCriterion("BAY_NO <>", value, "bayNo");
            return (Criteria) this;
        }

        public Criteria andBayNoGreaterThan(Short value) {
            addCriterion("BAY_NO >", value, "bayNo");
            return (Criteria) this;
        }

        public Criteria andBayNoGreaterThanOrEqualTo(Short value) {
            addCriterion("BAY_NO >=", value, "bayNo");
            return (Criteria) this;
        }

        public Criteria andBayNoLessThan(Short value) {
            addCriterion("BAY_NO <", value, "bayNo");
            return (Criteria) this;
        }

        public Criteria andBayNoLessThanOrEqualTo(Short value) {
            addCriterion("BAY_NO <=", value, "bayNo");
            return (Criteria) this;
        }

        public Criteria andBayNoIn(List<Short> values) {
            addCriterion("BAY_NO in", values, "bayNo");
            return (Criteria) this;
        }

        public Criteria andBayNoNotIn(List<Short> values) {
            addCriterion("BAY_NO not in", values, "bayNo");
            return (Criteria) this;
        }

        public Criteria andBayNoBetween(Short value1, Short value2) {
            addCriterion("BAY_NO between", value1, value2, "bayNo");
            return (Criteria) this;
        }

        public Criteria andBayNoNotBetween(Short value1, Short value2) {
            addCriterion("BAY_NO not between", value1, value2, "bayNo");
            return (Criteria) this;
        }

        public Criteria andRowNoIsNull() {
            addCriterion("ROW_NO is null");
            return (Criteria) this;
        }

        public Criteria andRowNoIsNotNull() {
            addCriterion("ROW_NO is not null");
            return (Criteria) this;
        }

        public Criteria andRowNoEqualTo(Short value) {
            addCriterion("ROW_NO =", value, "rowNo");
            return (Criteria) this;
        }

        public Criteria andRowNoNotEqualTo(Short value) {
            addCriterion("ROW_NO <>", value, "rowNo");
            return (Criteria) this;
        }

        public Criteria andRowNoGreaterThan(Short value) {
            addCriterion("ROW_NO >", value, "rowNo");
            return (Criteria) this;
        }

        public Criteria andRowNoGreaterThanOrEqualTo(Short value) {
            addCriterion("ROW_NO >=", value, "rowNo");
            return (Criteria) this;
        }

        public Criteria andRowNoLessThan(Short value) {
            addCriterion("ROW_NO <", value, "rowNo");
            return (Criteria) this;
        }

        public Criteria andRowNoLessThanOrEqualTo(Short value) {
            addCriterion("ROW_NO <=", value, "rowNo");
            return (Criteria) this;
        }

        public Criteria andRowNoIn(List<Short> values) {
            addCriterion("ROW_NO in", values, "rowNo");
            return (Criteria) this;
        }

        public Criteria andRowNoNotIn(List<Short> values) {
            addCriterion("ROW_NO not in", values, "rowNo");
            return (Criteria) this;
        }

        public Criteria andRowNoBetween(Short value1, Short value2) {
            addCriterion("ROW_NO between", value1, value2, "rowNo");
            return (Criteria) this;
        }

        public Criteria andRowNoNotBetween(Short value1, Short value2) {
            addCriterion("ROW_NO not between", value1, value2, "rowNo");
            return (Criteria) this;
        }

        public Criteria andTierNoIsNull() {
            addCriterion("TIER_NO is null");
            return (Criteria) this;
        }

        public Criteria andTierNoIsNotNull() {
            addCriterion("TIER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andTierNoEqualTo(Short value) {
            addCriterion("TIER_NO =", value, "tierNo");
            return (Criteria) this;
        }

        public Criteria andTierNoNotEqualTo(Short value) {
            addCriterion("TIER_NO <>", value, "tierNo");
            return (Criteria) this;
        }

        public Criteria andTierNoGreaterThan(Short value) {
            addCriterion("TIER_NO >", value, "tierNo");
            return (Criteria) this;
        }

        public Criteria andTierNoGreaterThanOrEqualTo(Short value) {
            addCriterion("TIER_NO >=", value, "tierNo");
            return (Criteria) this;
        }

        public Criteria andTierNoLessThan(Short value) {
            addCriterion("TIER_NO <", value, "tierNo");
            return (Criteria) this;
        }

        public Criteria andTierNoLessThanOrEqualTo(Short value) {
            addCriterion("TIER_NO <=", value, "tierNo");
            return (Criteria) this;
        }

        public Criteria andTierNoIn(List<Short> values) {
            addCriterion("TIER_NO in", values, "tierNo");
            return (Criteria) this;
        }

        public Criteria andTierNoNotIn(List<Short> values) {
            addCriterion("TIER_NO not in", values, "tierNo");
            return (Criteria) this;
        }

        public Criteria andTierNoBetween(Short value1, Short value2) {
            addCriterion("TIER_NO between", value1, value2, "tierNo");
            return (Criteria) this;
        }

        public Criteria andTierNoNotBetween(Short value1, Short value2) {
            addCriterion("TIER_NO not between", value1, value2, "tierNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoIsNull() {
            addCriterion("CNTR_NO is null");
            return (Criteria) this;
        }

        public Criteria andCntrNoIsNotNull() {
            addCriterion("CNTR_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCntrNoEqualTo(String value) {
            addCriterion("CNTR_NO =", value, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoNotEqualTo(String value) {
            addCriterion("CNTR_NO <>", value, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoGreaterThan(String value) {
            addCriterion("CNTR_NO >", value, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoGreaterThanOrEqualTo(String value) {
            addCriterion("CNTR_NO >=", value, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoLessThan(String value) {
            addCriterion("CNTR_NO <", value, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoLessThanOrEqualTo(String value) {
            addCriterion("CNTR_NO <=", value, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoLike(String value) {
            addCriterion("CNTR_NO like", value, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoNotLike(String value) {
            addCriterion("CNTR_NO not like", value, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoIn(List<String> values) {
            addCriterion("CNTR_NO in", values, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoNotIn(List<String> values) {
            addCriterion("CNTR_NO not in", values, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoBetween(String value1, String value2) {
            addCriterion("CNTR_NO between", value1, value2, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoNotBetween(String value1, String value2) {
            addCriterion("CNTR_NO not between", value1, value2, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrTypeIsNull() {
            addCriterion("CNTR_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCntrTypeIsNotNull() {
            addCriterion("CNTR_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCntrTypeEqualTo(String value) {
            addCriterion("CNTR_TYPE =", value, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeNotEqualTo(String value) {
            addCriterion("CNTR_TYPE <>", value, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeGreaterThan(String value) {
            addCriterion("CNTR_TYPE >", value, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CNTR_TYPE >=", value, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeLessThan(String value) {
            addCriterion("CNTR_TYPE <", value, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeLessThanOrEqualTo(String value) {
            addCriterion("CNTR_TYPE <=", value, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeLike(String value) {
            addCriterion("CNTR_TYPE like", value, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeNotLike(String value) {
            addCriterion("CNTR_TYPE not like", value, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeIn(List<String> values) {
            addCriterion("CNTR_TYPE in", values, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeNotIn(List<String> values) {
            addCriterion("CNTR_TYPE not in", values, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeBetween(String value1, String value2) {
            addCriterion("CNTR_TYPE between", value1, value2, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeNotBetween(String value1, String value2) {
            addCriterion("CNTR_TYPE not between", value1, value2, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrWeightIsNull() {
            addCriterion("CNTR_WEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andCntrWeightIsNotNull() {
            addCriterion("CNTR_WEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andCntrWeightEqualTo(Integer value) {
            addCriterion("CNTR_WEIGHT =", value, "cntrWeight");
            return (Criteria) this;
        }

        public Criteria andCntrWeightNotEqualTo(Integer value) {
            addCriterion("CNTR_WEIGHT <>", value, "cntrWeight");
            return (Criteria) this;
        }

        public Criteria andCntrWeightGreaterThan(Integer value) {
            addCriterion("CNTR_WEIGHT >", value, "cntrWeight");
            return (Criteria) this;
        }

        public Criteria andCntrWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("CNTR_WEIGHT >=", value, "cntrWeight");
            return (Criteria) this;
        }

        public Criteria andCntrWeightLessThan(Integer value) {
            addCriterion("CNTR_WEIGHT <", value, "cntrWeight");
            return (Criteria) this;
        }

        public Criteria andCntrWeightLessThanOrEqualTo(Integer value) {
            addCriterion("CNTR_WEIGHT <=", value, "cntrWeight");
            return (Criteria) this;
        }

        public Criteria andCntrWeightIn(List<Integer> values) {
            addCriterion("CNTR_WEIGHT in", values, "cntrWeight");
            return (Criteria) this;
        }

        public Criteria andCntrWeightNotIn(List<Integer> values) {
            addCriterion("CNTR_WEIGHT not in", values, "cntrWeight");
            return (Criteria) this;
        }

        public Criteria andCntrWeightBetween(Integer value1, Integer value2) {
            addCriterion("CNTR_WEIGHT between", value1, value2, "cntrWeight");
            return (Criteria) this;
        }

        public Criteria andCntrWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("CNTR_WEIGHT not between", value1, value2, "cntrWeight");
            return (Criteria) this;
        }

        public Criteria andDoorDirectIsNull() {
            addCriterion("DOOR_DIRECT is null");
            return (Criteria) this;
        }

        public Criteria andDoorDirectIsNotNull() {
            addCriterion("DOOR_DIRECT is not null");
            return (Criteria) this;
        }

        public Criteria andDoorDirectEqualTo(Short value) {
            addCriterion("DOOR_DIRECT =", value, "doorDirect");
            return (Criteria) this;
        }

        public Criteria andDoorDirectNotEqualTo(Short value) {
            addCriterion("DOOR_DIRECT <>", value, "doorDirect");
            return (Criteria) this;
        }

        public Criteria andDoorDirectGreaterThan(Short value) {
            addCriterion("DOOR_DIRECT >", value, "doorDirect");
            return (Criteria) this;
        }

        public Criteria andDoorDirectGreaterThanOrEqualTo(Short value) {
            addCriterion("DOOR_DIRECT >=", value, "doorDirect");
            return (Criteria) this;
        }

        public Criteria andDoorDirectLessThan(Short value) {
            addCriterion("DOOR_DIRECT <", value, "doorDirect");
            return (Criteria) this;
        }

        public Criteria andDoorDirectLessThanOrEqualTo(Short value) {
            addCriterion("DOOR_DIRECT <=", value, "doorDirect");
            return (Criteria) this;
        }

        public Criteria andDoorDirectIn(List<Short> values) {
            addCriterion("DOOR_DIRECT in", values, "doorDirect");
            return (Criteria) this;
        }

        public Criteria andDoorDirectNotIn(List<Short> values) {
            addCriterion("DOOR_DIRECT not in", values, "doorDirect");
            return (Criteria) this;
        }

        public Criteria andDoorDirectBetween(Short value1, Short value2) {
            addCriterion("DOOR_DIRECT between", value1, value2, "doorDirect");
            return (Criteria) this;
        }

        public Criteria andDoorDirectNotBetween(Short value1, Short value2) {
            addCriterion("DOOR_DIRECT not between", value1, value2, "doorDirect");
            return (Criteria) this;
        }

        public Criteria andSlotStatusIsNull() {
            addCriterion("SLOT_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andSlotStatusIsNotNull() {
            addCriterion("SLOT_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSlotStatusEqualTo(Integer value) {
            addCriterion("SLOT_STATUS =", value, "slotStatus");
            return (Criteria) this;
        }

        public Criteria andSlotStatusNotEqualTo(Integer value) {
            addCriterion("SLOT_STATUS <>", value, "slotStatus");
            return (Criteria) this;
        }

        public Criteria andSlotStatusGreaterThan(Integer value) {
            addCriterion("SLOT_STATUS >", value, "slotStatus");
            return (Criteria) this;
        }

        public Criteria andSlotStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("SLOT_STATUS >=", value, "slotStatus");
            return (Criteria) this;
        }

        public Criteria andSlotStatusLessThan(Integer value) {
            addCriterion("SLOT_STATUS <", value, "slotStatus");
            return (Criteria) this;
        }

        public Criteria andSlotStatusLessThanOrEqualTo(Integer value) {
            addCriterion("SLOT_STATUS <=", value, "slotStatus");
            return (Criteria) this;
        }

        public Criteria andSlotStatusIn(List<Integer> values) {
            addCriterion("SLOT_STATUS in", values, "slotStatus");
            return (Criteria) this;
        }

        public Criteria andSlotStatusNotIn(List<Integer> values) {
            addCriterion("SLOT_STATUS not in", values, "slotStatus");
            return (Criteria) this;
        }

        public Criteria andSlotStatusBetween(Integer value1, Integer value2) {
            addCriterion("SLOT_STATUS between", value1, value2, "slotStatus");
            return (Criteria) this;
        }

        public Criteria andSlotStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("SLOT_STATUS not between", value1, value2, "slotStatus");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("MODIFY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("MODIFY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("MODIFY_DATE =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("MODIFY_DATE <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("MODIFY_DATE >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("MODIFY_DATE <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("MODIFY_DATE in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("MODIFY_DATE not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andUpdateIndIsNull() {
            addCriterion("UPDATE_IND is null");
            return (Criteria) this;
        }

        public Criteria andUpdateIndIsNotNull() {
            addCriterion("UPDATE_IND is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateIndEqualTo(String value) {
            addCriterion("UPDATE_IND =", value, "updateInd");
            return (Criteria) this;
        }

        public Criteria andUpdateIndNotEqualTo(String value) {
            addCriterion("UPDATE_IND <>", value, "updateInd");
            return (Criteria) this;
        }

        public Criteria andUpdateIndGreaterThan(String value) {
            addCriterion("UPDATE_IND >", value, "updateInd");
            return (Criteria) this;
        }

        public Criteria andUpdateIndGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_IND >=", value, "updateInd");
            return (Criteria) this;
        }

        public Criteria andUpdateIndLessThan(String value) {
            addCriterion("UPDATE_IND <", value, "updateInd");
            return (Criteria) this;
        }

        public Criteria andUpdateIndLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_IND <=", value, "updateInd");
            return (Criteria) this;
        }

        public Criteria andUpdateIndLike(String value) {
            addCriterion("UPDATE_IND like", value, "updateInd");
            return (Criteria) this;
        }

        public Criteria andUpdateIndNotLike(String value) {
            addCriterion("UPDATE_IND not like", value, "updateInd");
            return (Criteria) this;
        }

        public Criteria andUpdateIndIn(List<String> values) {
            addCriterion("UPDATE_IND in", values, "updateInd");
            return (Criteria) this;
        }

        public Criteria andUpdateIndNotIn(List<String> values) {
            addCriterion("UPDATE_IND not in", values, "updateInd");
            return (Criteria) this;
        }

        public Criteria andUpdateIndBetween(String value1, String value2) {
            addCriterion("UPDATE_IND between", value1, value2, "updateInd");
            return (Criteria) this;
        }

        public Criteria andUpdateIndNotBetween(String value1, String value2) {
            addCriterion("UPDATE_IND not between", value1, value2, "updateInd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ARMGSLOTXJD
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ARMGSLOTXJD
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}