package com.example.dao.entity;

import java.util.Date;

public class Armgslotxjd extends ArmgslotxjdKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTXJD.CNTR_NO
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    private String cntrNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTXJD.CNTR_TYPE
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    private String cntrType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTXJD.CNTR_WEIGHT
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    private Integer cntrWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTXJD.DOOR_DIRECT
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    private Short doorDirect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTXJD.SLOT_STATUS
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    private Integer slotStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTXJD.MODIFY_DATE
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTXJD.UPDATE_IND
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    private String updateInd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTXJD.CNTR_NO
     *
     * @return the value of ARMGSLOTXJD.CNTR_NO
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public String getCntrNo() {
        return cntrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTXJD.CNTR_NO
     *
     * @param cntrNo the value for ARMGSLOTXJD.CNTR_NO
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public void setCntrNo(String cntrNo) {
        this.cntrNo = cntrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTXJD.CNTR_TYPE
     *
     * @return the value of ARMGSLOTXJD.CNTR_TYPE
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public String getCntrType() {
        return cntrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTXJD.CNTR_TYPE
     *
     * @param cntrType the value for ARMGSLOTXJD.CNTR_TYPE
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public void setCntrType(String cntrType) {
        this.cntrType = cntrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTXJD.CNTR_WEIGHT
     *
     * @return the value of ARMGSLOTXJD.CNTR_WEIGHT
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public Integer getCntrWeight() {
        return cntrWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTXJD.CNTR_WEIGHT
     *
     * @param cntrWeight the value for ARMGSLOTXJD.CNTR_WEIGHT
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public void setCntrWeight(Integer cntrWeight) {
        this.cntrWeight = cntrWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTXJD.DOOR_DIRECT
     *
     * @return the value of ARMGSLOTXJD.DOOR_DIRECT
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public Short getDoorDirect() {
        return doorDirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTXJD.DOOR_DIRECT
     *
     * @param doorDirect the value for ARMGSLOTXJD.DOOR_DIRECT
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public void setDoorDirect(Short doorDirect) {
        this.doorDirect = doorDirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTXJD.SLOT_STATUS
     *
     * @return the value of ARMGSLOTXJD.SLOT_STATUS
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public Integer getSlotStatus() {
        return slotStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTXJD.SLOT_STATUS
     *
     * @param slotStatus the value for ARMGSLOTXJD.SLOT_STATUS
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public void setSlotStatus(Integer slotStatus) {
        this.slotStatus = slotStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTXJD.MODIFY_DATE
     *
     * @return the value of ARMGSLOTXJD.MODIFY_DATE
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTXJD.MODIFY_DATE
     *
     * @param modifyDate the value for ARMGSLOTXJD.MODIFY_DATE
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTXJD.UPDATE_IND
     *
     * @return the value of ARMGSLOTXJD.UPDATE_IND
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public String getUpdateInd() {
        return updateInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTXJD.UPDATE_IND
     *
     * @param updateInd the value for ARMGSLOTXJD.UPDATE_IND
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public void setUpdateInd(String updateInd) {
        this.updateInd = updateInd;
    }
}