package com.example.dao.entity;

public class ArmgslotxjdKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTXJD.BLOCK_NO
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    private String blockNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTXJD.BAY_NO
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    private Short bayNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTXJD.ROW_NO
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    private Short rowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTXJD.TIER_NO
     *
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    private Short tierNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTXJD.BLOCK_NO
     *
     * @return the value of ARMGSLOTXJD.BLOCK_NO
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public String getBlockNo() {
        return blockNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTXJD.BLOCK_NO
     *
     * @param blockNo the value for ARMGSLOTXJD.BLOCK_NO
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public void setBlockNo(String blockNo) {
        this.blockNo = blockNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTXJD.BAY_NO
     *
     * @return the value of ARMGSLOTXJD.BAY_NO
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public Short getBayNo() {
        return bayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTXJD.BAY_NO
     *
     * @param bayNo the value for ARMGSLOTXJD.BAY_NO
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public void setBayNo(Short bayNo) {
        this.bayNo = bayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTXJD.ROW_NO
     *
     * @return the value of ARMGSLOTXJD.ROW_NO
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public Short getRowNo() {
        return rowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTXJD.ROW_NO
     *
     * @param rowNo the value for ARMGSLOTXJD.ROW_NO
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public void setRowNo(Short rowNo) {
        this.rowNo = rowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTXJD.TIER_NO
     *
     * @return the value of ARMGSLOTXJD.TIER_NO
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public Short getTierNo() {
        return tierNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTXJD.TIER_NO
     *
     * @param tierNo the value for ARMGSLOTXJD.TIER_NO
     * @mbg.generated Mon Nov 12 12:15:00 GMT+08:00 2018
     */
    public void setTierNo(Short tierNo) {
        this.tierNo = tierNo;
    }
}