package com.example.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ArmgjobqExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public ArmgjobqExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJobOrderSeqMsIsNull() {
            addCriterion("JOB_ORDER_SEQ_MS is null");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsIsNotNull() {
            addCriterion("JOB_ORDER_SEQ_MS is not null");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsEqualTo(Long value) {
            addCriterion("JOB_ORDER_SEQ_MS =", value, "jobOrderSeqMs");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsNotEqualTo(Long value) {
            addCriterion("JOB_ORDER_SEQ_MS <>", value, "jobOrderSeqMs");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsGreaterThan(Long value) {
            addCriterion("JOB_ORDER_SEQ_MS >", value, "jobOrderSeqMs");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsGreaterThanOrEqualTo(Long value) {
            addCriterion("JOB_ORDER_SEQ_MS >=", value, "jobOrderSeqMs");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsLessThan(Long value) {
            addCriterion("JOB_ORDER_SEQ_MS <", value, "jobOrderSeqMs");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsLessThanOrEqualTo(Long value) {
            addCriterion("JOB_ORDER_SEQ_MS <=", value, "jobOrderSeqMs");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsIn(List<Long> values) {
            addCriterion("JOB_ORDER_SEQ_MS in", values, "jobOrderSeqMs");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsNotIn(List<Long> values) {
            addCriterion("JOB_ORDER_SEQ_MS not in", values, "jobOrderSeqMs");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsBetween(Long value1, Long value2) {
            addCriterion("JOB_ORDER_SEQ_MS between", value1, value2, "jobOrderSeqMs");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqMsNotBetween(Long value1, Long value2) {
            addCriterion("JOB_ORDER_SEQ_MS not between", value1, value2, "jobOrderSeqMs");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtIsNull() {
            addCriterion("JOB_ORDER_SEQ_DT is null");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtIsNotNull() {
            addCriterion("JOB_ORDER_SEQ_DT is not null");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtEqualTo(Short value) {
            addCriterion("JOB_ORDER_SEQ_DT =", value, "jobOrderSeqDt");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtNotEqualTo(Short value) {
            addCriterion("JOB_ORDER_SEQ_DT <>", value, "jobOrderSeqDt");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtGreaterThan(Short value) {
            addCriterion("JOB_ORDER_SEQ_DT >", value, "jobOrderSeqDt");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtGreaterThanOrEqualTo(Short value) {
            addCriterion("JOB_ORDER_SEQ_DT >=", value, "jobOrderSeqDt");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtLessThan(Short value) {
            addCriterion("JOB_ORDER_SEQ_DT <", value, "jobOrderSeqDt");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtLessThanOrEqualTo(Short value) {
            addCriterion("JOB_ORDER_SEQ_DT <=", value, "jobOrderSeqDt");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtIn(List<Short> values) {
            addCriterion("JOB_ORDER_SEQ_DT in", values, "jobOrderSeqDt");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtNotIn(List<Short> values) {
            addCriterion("JOB_ORDER_SEQ_DT not in", values, "jobOrderSeqDt");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtBetween(Short value1, Short value2) {
            addCriterion("JOB_ORDER_SEQ_DT between", value1, value2, "jobOrderSeqDt");
            return (Criteria) this;
        }

        public Criteria andJobOrderSeqDtNotBetween(Short value1, Short value2) {
            addCriterion("JOB_ORDER_SEQ_DT not between", value1, value2, "jobOrderSeqDt");
            return (Criteria) this;
        }

        public Criteria andJobStatusQfrIsNull() {
            addCriterion("JOB_STATUS_QFR is null");
            return (Criteria) this;
        }

        public Criteria andJobStatusQfrIsNotNull() {
            addCriterion("JOB_STATUS_QFR is not null");
            return (Criteria) this;
        }

        public Criteria andJobStatusQfrEqualTo(String value) {
            addCriterion("JOB_STATUS_QFR =", value, "jobStatusQfr");
            return (Criteria) this;
        }

        public Criteria andJobStatusQfrNotEqualTo(String value) {
            addCriterion("JOB_STATUS_QFR <>", value, "jobStatusQfr");
            return (Criteria) this;
        }

        public Criteria andJobStatusQfrGreaterThan(String value) {
            addCriterion("JOB_STATUS_QFR >", value, "jobStatusQfr");
            return (Criteria) this;
        }

        public Criteria andJobStatusQfrGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_STATUS_QFR >=", value, "jobStatusQfr");
            return (Criteria) this;
        }

        public Criteria andJobStatusQfrLessThan(String value) {
            addCriterion("JOB_STATUS_QFR <", value, "jobStatusQfr");
            return (Criteria) this;
        }

        public Criteria andJobStatusQfrLessThanOrEqualTo(String value) {
            addCriterion("JOB_STATUS_QFR <=", value, "jobStatusQfr");
            return (Criteria) this;
        }

        public Criteria andJobStatusQfrLike(String value) {
            addCriterion("JOB_STATUS_QFR like", value, "jobStatusQfr");
            return (Criteria) this;
        }

        public Criteria andJobStatusQfrNotLike(String value) {
            addCriterion("JOB_STATUS_QFR not like", value, "jobStatusQfr");
            return (Criteria) this;
        }

        public Criteria andJobStatusQfrIn(List<String> values) {
            addCriterion("JOB_STATUS_QFR in", values, "jobStatusQfr");
            return (Criteria) this;
        }

        public Criteria andJobStatusQfrNotIn(List<String> values) {
            addCriterion("JOB_STATUS_QFR not in", values, "jobStatusQfr");
            return (Criteria) this;
        }

        public Criteria andJobStatusQfrBetween(String value1, String value2) {
            addCriterion("JOB_STATUS_QFR between", value1, value2, "jobStatusQfr");
            return (Criteria) this;
        }

        public Criteria andJobStatusQfrNotBetween(String value1, String value2) {
            addCriterion("JOB_STATUS_QFR not between", value1, value2, "jobStatusQfr");
            return (Criteria) this;
        }

        public Criteria andJobMotionQfrIsNull() {
            addCriterion("JOB_MOTION_QFR is null");
            return (Criteria) this;
        }

        public Criteria andJobMotionQfrIsNotNull() {
            addCriterion("JOB_MOTION_QFR is not null");
            return (Criteria) this;
        }

        public Criteria andJobMotionQfrEqualTo(String value) {
            addCriterion("JOB_MOTION_QFR =", value, "jobMotionQfr");
            return (Criteria) this;
        }

        public Criteria andJobMotionQfrNotEqualTo(String value) {
            addCriterion("JOB_MOTION_QFR <>", value, "jobMotionQfr");
            return (Criteria) this;
        }

        public Criteria andJobMotionQfrGreaterThan(String value) {
            addCriterion("JOB_MOTION_QFR >", value, "jobMotionQfr");
            return (Criteria) this;
        }

        public Criteria andJobMotionQfrGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_MOTION_QFR >=", value, "jobMotionQfr");
            return (Criteria) this;
        }

        public Criteria andJobMotionQfrLessThan(String value) {
            addCriterion("JOB_MOTION_QFR <", value, "jobMotionQfr");
            return (Criteria) this;
        }

        public Criteria andJobMotionQfrLessThanOrEqualTo(String value) {
            addCriterion("JOB_MOTION_QFR <=", value, "jobMotionQfr");
            return (Criteria) this;
        }

        public Criteria andJobMotionQfrLike(String value) {
            addCriterion("JOB_MOTION_QFR like", value, "jobMotionQfr");
            return (Criteria) this;
        }

        public Criteria andJobMotionQfrNotLike(String value) {
            addCriterion("JOB_MOTION_QFR not like", value, "jobMotionQfr");
            return (Criteria) this;
        }

        public Criteria andJobMotionQfrIn(List<String> values) {
            addCriterion("JOB_MOTION_QFR in", values, "jobMotionQfr");
            return (Criteria) this;
        }

        public Criteria andJobMotionQfrNotIn(List<String> values) {
            addCriterion("JOB_MOTION_QFR not in", values, "jobMotionQfr");
            return (Criteria) this;
        }

        public Criteria andJobMotionQfrBetween(String value1, String value2) {
            addCriterion("JOB_MOTION_QFR between", value1, value2, "jobMotionQfr");
            return (Criteria) this;
        }

        public Criteria andJobMotionQfrNotBetween(String value1, String value2) {
            addCriterion("JOB_MOTION_QFR not between", value1, value2, "jobMotionQfr");
            return (Criteria) this;
        }

        public Criteria andPriorityWeightIsNull() {
            addCriterion("PRIORITY_WEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andPriorityWeightIsNotNull() {
            addCriterion("PRIORITY_WEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityWeightEqualTo(Integer value) {
            addCriterion("PRIORITY_WEIGHT =", value, "priorityWeight");
            return (Criteria) this;
        }

        public Criteria andPriorityWeightNotEqualTo(Integer value) {
            addCriterion("PRIORITY_WEIGHT <>", value, "priorityWeight");
            return (Criteria) this;
        }

        public Criteria andPriorityWeightGreaterThan(Integer value) {
            addCriterion("PRIORITY_WEIGHT >", value, "priorityWeight");
            return (Criteria) this;
        }

        public Criteria andPriorityWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("PRIORITY_WEIGHT >=", value, "priorityWeight");
            return (Criteria) this;
        }

        public Criteria andPriorityWeightLessThan(Integer value) {
            addCriterion("PRIORITY_WEIGHT <", value, "priorityWeight");
            return (Criteria) this;
        }

        public Criteria andPriorityWeightLessThanOrEqualTo(Integer value) {
            addCriterion("PRIORITY_WEIGHT <=", value, "priorityWeight");
            return (Criteria) this;
        }

        public Criteria andPriorityWeightIn(List<Integer> values) {
            addCriterion("PRIORITY_WEIGHT in", values, "priorityWeight");
            return (Criteria) this;
        }

        public Criteria andPriorityWeightNotIn(List<Integer> values) {
            addCriterion("PRIORITY_WEIGHT not in", values, "priorityWeight");
            return (Criteria) this;
        }

        public Criteria andPriorityWeightBetween(Integer value1, Integer value2) {
            addCriterion("PRIORITY_WEIGHT between", value1, value2, "priorityWeight");
            return (Criteria) this;
        }

        public Criteria andPriorityWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("PRIORITY_WEIGHT not between", value1, value2, "priorityWeight");
            return (Criteria) this;
        }

        public Criteria andArmgIdIsNull() {
            addCriterion("ARMG_ID is null");
            return (Criteria) this;
        }

        public Criteria andArmgIdIsNotNull() {
            addCriterion("ARMG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andArmgIdEqualTo(String value) {
            addCriterion("ARMG_ID =", value, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdNotEqualTo(String value) {
            addCriterion("ARMG_ID <>", value, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdGreaterThan(String value) {
            addCriterion("ARMG_ID >", value, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdGreaterThanOrEqualTo(String value) {
            addCriterion("ARMG_ID >=", value, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdLessThan(String value) {
            addCriterion("ARMG_ID <", value, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdLessThanOrEqualTo(String value) {
            addCriterion("ARMG_ID <=", value, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdLike(String value) {
            addCriterion("ARMG_ID like", value, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdNotLike(String value) {
            addCriterion("ARMG_ID not like", value, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdIn(List<String> values) {
            addCriterion("ARMG_ID in", values, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdNotIn(List<String> values) {
            addCriterion("ARMG_ID not in", values, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdBetween(String value1, String value2) {
            addCriterion("ARMG_ID between", value1, value2, "armgId");
            return (Criteria) this;
        }

        public Criteria andArmgIdNotBetween(String value1, String value2) {
            addCriterion("ARMG_ID not between", value1, value2, "armgId");
            return (Criteria) this;
        }

        public Criteria andWhoAssignIsNull() {
            addCriterion("WHO_ASSIGN is null");
            return (Criteria) this;
        }

        public Criteria andWhoAssignIsNotNull() {
            addCriterion("WHO_ASSIGN is not null");
            return (Criteria) this;
        }

        public Criteria andWhoAssignEqualTo(String value) {
            addCriterion("WHO_ASSIGN =", value, "whoAssign");
            return (Criteria) this;
        }

        public Criteria andWhoAssignNotEqualTo(String value) {
            addCriterion("WHO_ASSIGN <>", value, "whoAssign");
            return (Criteria) this;
        }

        public Criteria andWhoAssignGreaterThan(String value) {
            addCriterion("WHO_ASSIGN >", value, "whoAssign");
            return (Criteria) this;
        }

        public Criteria andWhoAssignGreaterThanOrEqualTo(String value) {
            addCriterion("WHO_ASSIGN >=", value, "whoAssign");
            return (Criteria) this;
        }

        public Criteria andWhoAssignLessThan(String value) {
            addCriterion("WHO_ASSIGN <", value, "whoAssign");
            return (Criteria) this;
        }

        public Criteria andWhoAssignLessThanOrEqualTo(String value) {
            addCriterion("WHO_ASSIGN <=", value, "whoAssign");
            return (Criteria) this;
        }

        public Criteria andWhoAssignLike(String value) {
            addCriterion("WHO_ASSIGN like", value, "whoAssign");
            return (Criteria) this;
        }

        public Criteria andWhoAssignNotLike(String value) {
            addCriterion("WHO_ASSIGN not like", value, "whoAssign");
            return (Criteria) this;
        }

        public Criteria andWhoAssignIn(List<String> values) {
            addCriterion("WHO_ASSIGN in", values, "whoAssign");
            return (Criteria) this;
        }

        public Criteria andWhoAssignNotIn(List<String> values) {
            addCriterion("WHO_ASSIGN not in", values, "whoAssign");
            return (Criteria) this;
        }

        public Criteria andWhoAssignBetween(String value1, String value2) {
            addCriterion("WHO_ASSIGN between", value1, value2, "whoAssign");
            return (Criteria) this;
        }

        public Criteria andWhoAssignNotBetween(String value1, String value2) {
            addCriterion("WHO_ASSIGN not between", value1, value2, "whoAssign");
            return (Criteria) this;
        }

        public Criteria andBlockFromIsNull() {
            addCriterion("BLOCK_FROM is null");
            return (Criteria) this;
        }

        public Criteria andBlockFromIsNotNull() {
            addCriterion("BLOCK_FROM is not null");
            return (Criteria) this;
        }

        public Criteria andBlockFromEqualTo(String value) {
            addCriterion("BLOCK_FROM =", value, "blockFrom");
            return (Criteria) this;
        }

        public Criteria andBlockFromNotEqualTo(String value) {
            addCriterion("BLOCK_FROM <>", value, "blockFrom");
            return (Criteria) this;
        }

        public Criteria andBlockFromGreaterThan(String value) {
            addCriterion("BLOCK_FROM >", value, "blockFrom");
            return (Criteria) this;
        }

        public Criteria andBlockFromGreaterThanOrEqualTo(String value) {
            addCriterion("BLOCK_FROM >=", value, "blockFrom");
            return (Criteria) this;
        }

        public Criteria andBlockFromLessThan(String value) {
            addCriterion("BLOCK_FROM <", value, "blockFrom");
            return (Criteria) this;
        }

        public Criteria andBlockFromLessThanOrEqualTo(String value) {
            addCriterion("BLOCK_FROM <=", value, "blockFrom");
            return (Criteria) this;
        }

        public Criteria andBlockFromLike(String value) {
            addCriterion("BLOCK_FROM like", value, "blockFrom");
            return (Criteria) this;
        }

        public Criteria andBlockFromNotLike(String value) {
            addCriterion("BLOCK_FROM not like", value, "blockFrom");
            return (Criteria) this;
        }

        public Criteria andBlockFromIn(List<String> values) {
            addCriterion("BLOCK_FROM in", values, "blockFrom");
            return (Criteria) this;
        }

        public Criteria andBlockFromNotIn(List<String> values) {
            addCriterion("BLOCK_FROM not in", values, "blockFrom");
            return (Criteria) this;
        }

        public Criteria andBlockFromBetween(String value1, String value2) {
            addCriterion("BLOCK_FROM between", value1, value2, "blockFrom");
            return (Criteria) this;
        }

        public Criteria andBlockFromNotBetween(String value1, String value2) {
            addCriterion("BLOCK_FROM not between", value1, value2, "blockFrom");
            return (Criteria) this;
        }

        public Criteria andBayFromIsNull() {
            addCriterion("BAY_FROM is null");
            return (Criteria) this;
        }

        public Criteria andBayFromIsNotNull() {
            addCriterion("BAY_FROM is not null");
            return (Criteria) this;
        }

        public Criteria andBayFromEqualTo(Short value) {
            addCriterion("BAY_FROM =", value, "bayFrom");
            return (Criteria) this;
        }

        public Criteria andBayFromNotEqualTo(Short value) {
            addCriterion("BAY_FROM <>", value, "bayFrom");
            return (Criteria) this;
        }

        public Criteria andBayFromGreaterThan(Short value) {
            addCriterion("BAY_FROM >", value, "bayFrom");
            return (Criteria) this;
        }

        public Criteria andBayFromGreaterThanOrEqualTo(Short value) {
            addCriterion("BAY_FROM >=", value, "bayFrom");
            return (Criteria) this;
        }

        public Criteria andBayFromLessThan(Short value) {
            addCriterion("BAY_FROM <", value, "bayFrom");
            return (Criteria) this;
        }

        public Criteria andBayFromLessThanOrEqualTo(Short value) {
            addCriterion("BAY_FROM <=", value, "bayFrom");
            return (Criteria) this;
        }

        public Criteria andBayFromIn(List<Short> values) {
            addCriterion("BAY_FROM in", values, "bayFrom");
            return (Criteria) this;
        }

        public Criteria andBayFromNotIn(List<Short> values) {
            addCriterion("BAY_FROM not in", values, "bayFrom");
            return (Criteria) this;
        }

        public Criteria andBayFromBetween(Short value1, Short value2) {
            addCriterion("BAY_FROM between", value1, value2, "bayFrom");
            return (Criteria) this;
        }

        public Criteria andBayFromNotBetween(Short value1, Short value2) {
            addCriterion("BAY_FROM not between", value1, value2, "bayFrom");
            return (Criteria) this;
        }

        public Criteria andRowFromIsNull() {
            addCriterion("ROW_FROM is null");
            return (Criteria) this;
        }

        public Criteria andRowFromIsNotNull() {
            addCriterion("ROW_FROM is not null");
            return (Criteria) this;
        }

        public Criteria andRowFromEqualTo(Short value) {
            addCriterion("ROW_FROM =", value, "rowFrom");
            return (Criteria) this;
        }

        public Criteria andRowFromNotEqualTo(Short value) {
            addCriterion("ROW_FROM <>", value, "rowFrom");
            return (Criteria) this;
        }

        public Criteria andRowFromGreaterThan(Short value) {
            addCriterion("ROW_FROM >", value, "rowFrom");
            return (Criteria) this;
        }

        public Criteria andRowFromGreaterThanOrEqualTo(Short value) {
            addCriterion("ROW_FROM >=", value, "rowFrom");
            return (Criteria) this;
        }

        public Criteria andRowFromLessThan(Short value) {
            addCriterion("ROW_FROM <", value, "rowFrom");
            return (Criteria) this;
        }

        public Criteria andRowFromLessThanOrEqualTo(Short value) {
            addCriterion("ROW_FROM <=", value, "rowFrom");
            return (Criteria) this;
        }

        public Criteria andRowFromIn(List<Short> values) {
            addCriterion("ROW_FROM in", values, "rowFrom");
            return (Criteria) this;
        }

        public Criteria andRowFromNotIn(List<Short> values) {
            addCriterion("ROW_FROM not in", values, "rowFrom");
            return (Criteria) this;
        }

        public Criteria andRowFromBetween(Short value1, Short value2) {
            addCriterion("ROW_FROM between", value1, value2, "rowFrom");
            return (Criteria) this;
        }

        public Criteria andRowFromNotBetween(Short value1, Short value2) {
            addCriterion("ROW_FROM not between", value1, value2, "rowFrom");
            return (Criteria) this;
        }

        public Criteria andTierFromIsNull() {
            addCriterion("TIER_FROM is null");
            return (Criteria) this;
        }

        public Criteria andTierFromIsNotNull() {
            addCriterion("TIER_FROM is not null");
            return (Criteria) this;
        }

        public Criteria andTierFromEqualTo(Short value) {
            addCriterion("TIER_FROM =", value, "tierFrom");
            return (Criteria) this;
        }

        public Criteria andTierFromNotEqualTo(Short value) {
            addCriterion("TIER_FROM <>", value, "tierFrom");
            return (Criteria) this;
        }

        public Criteria andTierFromGreaterThan(Short value) {
            addCriterion("TIER_FROM >", value, "tierFrom");
            return (Criteria) this;
        }

        public Criteria andTierFromGreaterThanOrEqualTo(Short value) {
            addCriterion("TIER_FROM >=", value, "tierFrom");
            return (Criteria) this;
        }

        public Criteria andTierFromLessThan(Short value) {
            addCriterion("TIER_FROM <", value, "tierFrom");
            return (Criteria) this;
        }

        public Criteria andTierFromLessThanOrEqualTo(Short value) {
            addCriterion("TIER_FROM <=", value, "tierFrom");
            return (Criteria) this;
        }

        public Criteria andTierFromIn(List<Short> values) {
            addCriterion("TIER_FROM in", values, "tierFrom");
            return (Criteria) this;
        }

        public Criteria andTierFromNotIn(List<Short> values) {
            addCriterion("TIER_FROM not in", values, "tierFrom");
            return (Criteria) this;
        }

        public Criteria andTierFromBetween(Short value1, Short value2) {
            addCriterion("TIER_FROM between", value1, value2, "tierFrom");
            return (Criteria) this;
        }

        public Criteria andTierFromNotBetween(Short value1, Short value2) {
            addCriterion("TIER_FROM not between", value1, value2, "tierFrom");
            return (Criteria) this;
        }

        public Criteria andDoorDirFromIsNull() {
            addCriterion("DOOR_DIR_FROM is null");
            return (Criteria) this;
        }

        public Criteria andDoorDirFromIsNotNull() {
            addCriterion("DOOR_DIR_FROM is not null");
            return (Criteria) this;
        }

        public Criteria andDoorDirFromEqualTo(Short value) {
            addCriterion("DOOR_DIR_FROM =", value, "doorDirFrom");
            return (Criteria) this;
        }

        public Criteria andDoorDirFromNotEqualTo(Short value) {
            addCriterion("DOOR_DIR_FROM <>", value, "doorDirFrom");
            return (Criteria) this;
        }

        public Criteria andDoorDirFromGreaterThan(Short value) {
            addCriterion("DOOR_DIR_FROM >", value, "doorDirFrom");
            return (Criteria) this;
        }

        public Criteria andDoorDirFromGreaterThanOrEqualTo(Short value) {
            addCriterion("DOOR_DIR_FROM >=", value, "doorDirFrom");
            return (Criteria) this;
        }

        public Criteria andDoorDirFromLessThan(Short value) {
            addCriterion("DOOR_DIR_FROM <", value, "doorDirFrom");
            return (Criteria) this;
        }

        public Criteria andDoorDirFromLessThanOrEqualTo(Short value) {
            addCriterion("DOOR_DIR_FROM <=", value, "doorDirFrom");
            return (Criteria) this;
        }

        public Criteria andDoorDirFromIn(List<Short> values) {
            addCriterion("DOOR_DIR_FROM in", values, "doorDirFrom");
            return (Criteria) this;
        }

        public Criteria andDoorDirFromNotIn(List<Short> values) {
            addCriterion("DOOR_DIR_FROM not in", values, "doorDirFrom");
            return (Criteria) this;
        }

        public Criteria andDoorDirFromBetween(Short value1, Short value2) {
            addCriterion("DOOR_DIR_FROM between", value1, value2, "doorDirFrom");
            return (Criteria) this;
        }

        public Criteria andDoorDirFromNotBetween(Short value1, Short value2) {
            addCriterion("DOOR_DIR_FROM not between", value1, value2, "doorDirFrom");
            return (Criteria) this;
        }

        public Criteria andBlockToIsNull() {
            addCriterion("BLOCK_TO is null");
            return (Criteria) this;
        }

        public Criteria andBlockToIsNotNull() {
            addCriterion("BLOCK_TO is not null");
            return (Criteria) this;
        }

        public Criteria andBlockToEqualTo(String value) {
            addCriterion("BLOCK_TO =", value, "blockTo");
            return (Criteria) this;
        }

        public Criteria andBlockToNotEqualTo(String value) {
            addCriterion("BLOCK_TO <>", value, "blockTo");
            return (Criteria) this;
        }

        public Criteria andBlockToGreaterThan(String value) {
            addCriterion("BLOCK_TO >", value, "blockTo");
            return (Criteria) this;
        }

        public Criteria andBlockToGreaterThanOrEqualTo(String value) {
            addCriterion("BLOCK_TO >=", value, "blockTo");
            return (Criteria) this;
        }

        public Criteria andBlockToLessThan(String value) {
            addCriterion("BLOCK_TO <", value, "blockTo");
            return (Criteria) this;
        }

        public Criteria andBlockToLessThanOrEqualTo(String value) {
            addCriterion("BLOCK_TO <=", value, "blockTo");
            return (Criteria) this;
        }

        public Criteria andBlockToLike(String value) {
            addCriterion("BLOCK_TO like", value, "blockTo");
            return (Criteria) this;
        }

        public Criteria andBlockToNotLike(String value) {
            addCriterion("BLOCK_TO not like", value, "blockTo");
            return (Criteria) this;
        }

        public Criteria andBlockToIn(List<String> values) {
            addCriterion("BLOCK_TO in", values, "blockTo");
            return (Criteria) this;
        }

        public Criteria andBlockToNotIn(List<String> values) {
            addCriterion("BLOCK_TO not in", values, "blockTo");
            return (Criteria) this;
        }

        public Criteria andBlockToBetween(String value1, String value2) {
            addCriterion("BLOCK_TO between", value1, value2, "blockTo");
            return (Criteria) this;
        }

        public Criteria andBlockToNotBetween(String value1, String value2) {
            addCriterion("BLOCK_TO not between", value1, value2, "blockTo");
            return (Criteria) this;
        }

        public Criteria andBayToIsNull() {
            addCriterion("BAY_TO is null");
            return (Criteria) this;
        }

        public Criteria andBayToIsNotNull() {
            addCriterion("BAY_TO is not null");
            return (Criteria) this;
        }

        public Criteria andBayToEqualTo(Short value) {
            addCriterion("BAY_TO =", value, "bayTo");
            return (Criteria) this;
        }

        public Criteria andBayToNotEqualTo(Short value) {
            addCriterion("BAY_TO <>", value, "bayTo");
            return (Criteria) this;
        }

        public Criteria andBayToGreaterThan(Short value) {
            addCriterion("BAY_TO >", value, "bayTo");
            return (Criteria) this;
        }

        public Criteria andBayToGreaterThanOrEqualTo(Short value) {
            addCriterion("BAY_TO >=", value, "bayTo");
            return (Criteria) this;
        }

        public Criteria andBayToLessThan(Short value) {
            addCriterion("BAY_TO <", value, "bayTo");
            return (Criteria) this;
        }

        public Criteria andBayToLessThanOrEqualTo(Short value) {
            addCriterion("BAY_TO <=", value, "bayTo");
            return (Criteria) this;
        }

        public Criteria andBayToIn(List<Short> values) {
            addCriterion("BAY_TO in", values, "bayTo");
            return (Criteria) this;
        }

        public Criteria andBayToNotIn(List<Short> values) {
            addCriterion("BAY_TO not in", values, "bayTo");
            return (Criteria) this;
        }

        public Criteria andBayToBetween(Short value1, Short value2) {
            addCriterion("BAY_TO between", value1, value2, "bayTo");
            return (Criteria) this;
        }

        public Criteria andBayToNotBetween(Short value1, Short value2) {
            addCriterion("BAY_TO not between", value1, value2, "bayTo");
            return (Criteria) this;
        }

        public Criteria andRowToIsNull() {
            addCriterion("ROW_TO is null");
            return (Criteria) this;
        }

        public Criteria andRowToIsNotNull() {
            addCriterion("ROW_TO is not null");
            return (Criteria) this;
        }

        public Criteria andRowToEqualTo(Short value) {
            addCriterion("ROW_TO =", value, "rowTo");
            return (Criteria) this;
        }

        public Criteria andRowToNotEqualTo(Short value) {
            addCriterion("ROW_TO <>", value, "rowTo");
            return (Criteria) this;
        }

        public Criteria andRowToGreaterThan(Short value) {
            addCriterion("ROW_TO >", value, "rowTo");
            return (Criteria) this;
        }

        public Criteria andRowToGreaterThanOrEqualTo(Short value) {
            addCriterion("ROW_TO >=", value, "rowTo");
            return (Criteria) this;
        }

        public Criteria andRowToLessThan(Short value) {
            addCriterion("ROW_TO <", value, "rowTo");
            return (Criteria) this;
        }

        public Criteria andRowToLessThanOrEqualTo(Short value) {
            addCriterion("ROW_TO <=", value, "rowTo");
            return (Criteria) this;
        }

        public Criteria andRowToIn(List<Short> values) {
            addCriterion("ROW_TO in", values, "rowTo");
            return (Criteria) this;
        }

        public Criteria andRowToNotIn(List<Short> values) {
            addCriterion("ROW_TO not in", values, "rowTo");
            return (Criteria) this;
        }

        public Criteria andRowToBetween(Short value1, Short value2) {
            addCriterion("ROW_TO between", value1, value2, "rowTo");
            return (Criteria) this;
        }

        public Criteria andRowToNotBetween(Short value1, Short value2) {
            addCriterion("ROW_TO not between", value1, value2, "rowTo");
            return (Criteria) this;
        }

        public Criteria andTierToIsNull() {
            addCriterion("TIER_TO is null");
            return (Criteria) this;
        }

        public Criteria andTierToIsNotNull() {
            addCriterion("TIER_TO is not null");
            return (Criteria) this;
        }

        public Criteria andTierToEqualTo(Short value) {
            addCriterion("TIER_TO =", value, "tierTo");
            return (Criteria) this;
        }

        public Criteria andTierToNotEqualTo(Short value) {
            addCriterion("TIER_TO <>", value, "tierTo");
            return (Criteria) this;
        }

        public Criteria andTierToGreaterThan(Short value) {
            addCriterion("TIER_TO >", value, "tierTo");
            return (Criteria) this;
        }

        public Criteria andTierToGreaterThanOrEqualTo(Short value) {
            addCriterion("TIER_TO >=", value, "tierTo");
            return (Criteria) this;
        }

        public Criteria andTierToLessThan(Short value) {
            addCriterion("TIER_TO <", value, "tierTo");
            return (Criteria) this;
        }

        public Criteria andTierToLessThanOrEqualTo(Short value) {
            addCriterion("TIER_TO <=", value, "tierTo");
            return (Criteria) this;
        }

        public Criteria andTierToIn(List<Short> values) {
            addCriterion("TIER_TO in", values, "tierTo");
            return (Criteria) this;
        }

        public Criteria andTierToNotIn(List<Short> values) {
            addCriterion("TIER_TO not in", values, "tierTo");
            return (Criteria) this;
        }

        public Criteria andTierToBetween(Short value1, Short value2) {
            addCriterion("TIER_TO between", value1, value2, "tierTo");
            return (Criteria) this;
        }

        public Criteria andTierToNotBetween(Short value1, Short value2) {
            addCriterion("TIER_TO not between", value1, value2, "tierTo");
            return (Criteria) this;
        }

        public Criteria andDoorDirToIsNull() {
            addCriterion("DOOR_DIR_TO is null");
            return (Criteria) this;
        }

        public Criteria andDoorDirToIsNotNull() {
            addCriterion("DOOR_DIR_TO is not null");
            return (Criteria) this;
        }

        public Criteria andDoorDirToEqualTo(Short value) {
            addCriterion("DOOR_DIR_TO =", value, "doorDirTo");
            return (Criteria) this;
        }

        public Criteria andDoorDirToNotEqualTo(Short value) {
            addCriterion("DOOR_DIR_TO <>", value, "doorDirTo");
            return (Criteria) this;
        }

        public Criteria andDoorDirToGreaterThan(Short value) {
            addCriterion("DOOR_DIR_TO >", value, "doorDirTo");
            return (Criteria) this;
        }

        public Criteria andDoorDirToGreaterThanOrEqualTo(Short value) {
            addCriterion("DOOR_DIR_TO >=", value, "doorDirTo");
            return (Criteria) this;
        }

        public Criteria andDoorDirToLessThan(Short value) {
            addCriterion("DOOR_DIR_TO <", value, "doorDirTo");
            return (Criteria) this;
        }

        public Criteria andDoorDirToLessThanOrEqualTo(Short value) {
            addCriterion("DOOR_DIR_TO <=", value, "doorDirTo");
            return (Criteria) this;
        }

        public Criteria andDoorDirToIn(List<Short> values) {
            addCriterion("DOOR_DIR_TO in", values, "doorDirTo");
            return (Criteria) this;
        }

        public Criteria andDoorDirToNotIn(List<Short> values) {
            addCriterion("DOOR_DIR_TO not in", values, "doorDirTo");
            return (Criteria) this;
        }

        public Criteria andDoorDirToBetween(Short value1, Short value2) {
            addCriterion("DOOR_DIR_TO between", value1, value2, "doorDirTo");
            return (Criteria) this;
        }

        public Criteria andDoorDirToNotBetween(Short value1, Short value2) {
            addCriterion("DOOR_DIR_TO not between", value1, value2, "doorDirTo");
            return (Criteria) this;
        }

        public Criteria andChassisTypeIsNull() {
            addCriterion("CHASSIS_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andChassisTypeIsNotNull() {
            addCriterion("CHASSIS_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andChassisTypeEqualTo(Short value) {
            addCriterion("CHASSIS_TYPE =", value, "chassisType");
            return (Criteria) this;
        }

        public Criteria andChassisTypeNotEqualTo(Short value) {
            addCriterion("CHASSIS_TYPE <>", value, "chassisType");
            return (Criteria) this;
        }

        public Criteria andChassisTypeGreaterThan(Short value) {
            addCriterion("CHASSIS_TYPE >", value, "chassisType");
            return (Criteria) this;
        }

        public Criteria andChassisTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("CHASSIS_TYPE >=", value, "chassisType");
            return (Criteria) this;
        }

        public Criteria andChassisTypeLessThan(Short value) {
            addCriterion("CHASSIS_TYPE <", value, "chassisType");
            return (Criteria) this;
        }

        public Criteria andChassisTypeLessThanOrEqualTo(Short value) {
            addCriterion("CHASSIS_TYPE <=", value, "chassisType");
            return (Criteria) this;
        }

        public Criteria andChassisTypeIn(List<Short> values) {
            addCriterion("CHASSIS_TYPE in", values, "chassisType");
            return (Criteria) this;
        }

        public Criteria andChassisTypeNotIn(List<Short> values) {
            addCriterion("CHASSIS_TYPE not in", values, "chassisType");
            return (Criteria) this;
        }

        public Criteria andChassisTypeBetween(Short value1, Short value2) {
            addCriterion("CHASSIS_TYPE between", value1, value2, "chassisType");
            return (Criteria) this;
        }

        public Criteria andChassisTypeNotBetween(Short value1, Short value2) {
            addCriterion("CHASSIS_TYPE not between", value1, value2, "chassisType");
            return (Criteria) this;
        }

        public Criteria andChassisNoIsNull() {
            addCriterion("CHASSIS_NO is null");
            return (Criteria) this;
        }

        public Criteria andChassisNoIsNotNull() {
            addCriterion("CHASSIS_NO is not null");
            return (Criteria) this;
        }

        public Criteria andChassisNoEqualTo(Integer value) {
            addCriterion("CHASSIS_NO =", value, "chassisNo");
            return (Criteria) this;
        }

        public Criteria andChassisNoNotEqualTo(Integer value) {
            addCriterion("CHASSIS_NO <>", value, "chassisNo");
            return (Criteria) this;
        }

        public Criteria andChassisNoGreaterThan(Integer value) {
            addCriterion("CHASSIS_NO >", value, "chassisNo");
            return (Criteria) this;
        }

        public Criteria andChassisNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("CHASSIS_NO >=", value, "chassisNo");
            return (Criteria) this;
        }

        public Criteria andChassisNoLessThan(Integer value) {
            addCriterion("CHASSIS_NO <", value, "chassisNo");
            return (Criteria) this;
        }

        public Criteria andChassisNoLessThanOrEqualTo(Integer value) {
            addCriterion("CHASSIS_NO <=", value, "chassisNo");
            return (Criteria) this;
        }

        public Criteria andChassisNoIn(List<Integer> values) {
            addCriterion("CHASSIS_NO in", values, "chassisNo");
            return (Criteria) this;
        }

        public Criteria andChassisNoNotIn(List<Integer> values) {
            addCriterion("CHASSIS_NO not in", values, "chassisNo");
            return (Criteria) this;
        }

        public Criteria andChassisNoBetween(Integer value1, Integer value2) {
            addCriterion("CHASSIS_NO between", value1, value2, "chassisNo");
            return (Criteria) this;
        }

        public Criteria andChassisNoNotBetween(Integer value1, Integer value2) {
            addCriterion("CHASSIS_NO not between", value1, value2, "chassisNo");
            return (Criteria) this;
        }

        public Criteria andPosOnChassisIsNull() {
            addCriterion("POS_ON_CHASSIS is null");
            return (Criteria) this;
        }

        public Criteria andPosOnChassisIsNotNull() {
            addCriterion("POS_ON_CHASSIS is not null");
            return (Criteria) this;
        }

        public Criteria andPosOnChassisEqualTo(Short value) {
            addCriterion("POS_ON_CHASSIS =", value, "posOnChassis");
            return (Criteria) this;
        }

        public Criteria andPosOnChassisNotEqualTo(Short value) {
            addCriterion("POS_ON_CHASSIS <>", value, "posOnChassis");
            return (Criteria) this;
        }

        public Criteria andPosOnChassisGreaterThan(Short value) {
            addCriterion("POS_ON_CHASSIS >", value, "posOnChassis");
            return (Criteria) this;
        }

        public Criteria andPosOnChassisGreaterThanOrEqualTo(Short value) {
            addCriterion("POS_ON_CHASSIS >=", value, "posOnChassis");
            return (Criteria) this;
        }

        public Criteria andPosOnChassisLessThan(Short value) {
            addCriterion("POS_ON_CHASSIS <", value, "posOnChassis");
            return (Criteria) this;
        }

        public Criteria andPosOnChassisLessThanOrEqualTo(Short value) {
            addCriterion("POS_ON_CHASSIS <=", value, "posOnChassis");
            return (Criteria) this;
        }

        public Criteria andPosOnChassisIn(List<Short> values) {
            addCriterion("POS_ON_CHASSIS in", values, "posOnChassis");
            return (Criteria) this;
        }

        public Criteria andPosOnChassisNotIn(List<Short> values) {
            addCriterion("POS_ON_CHASSIS not in", values, "posOnChassis");
            return (Criteria) this;
        }

        public Criteria andPosOnChassisBetween(Short value1, Short value2) {
            addCriterion("POS_ON_CHASSIS between", value1, value2, "posOnChassis");
            return (Criteria) this;
        }

        public Criteria andPosOnChassisNotBetween(Short value1, Short value2) {
            addCriterion("POS_ON_CHASSIS not between", value1, value2, "posOnChassis");
            return (Criteria) this;
        }

        public Criteria andPickupLandingIsNull() {
            addCriterion("PICKUP_LANDING is null");
            return (Criteria) this;
        }

        public Criteria andPickupLandingIsNotNull() {
            addCriterion("PICKUP_LANDING is not null");
            return (Criteria) this;
        }

        public Criteria andPickupLandingEqualTo(Short value) {
            addCriterion("PICKUP_LANDING =", value, "pickupLanding");
            return (Criteria) this;
        }

        public Criteria andPickupLandingNotEqualTo(Short value) {
            addCriterion("PICKUP_LANDING <>", value, "pickupLanding");
            return (Criteria) this;
        }

        public Criteria andPickupLandingGreaterThan(Short value) {
            addCriterion("PICKUP_LANDING >", value, "pickupLanding");
            return (Criteria) this;
        }

        public Criteria andPickupLandingGreaterThanOrEqualTo(Short value) {
            addCriterion("PICKUP_LANDING >=", value, "pickupLanding");
            return (Criteria) this;
        }

        public Criteria andPickupLandingLessThan(Short value) {
            addCriterion("PICKUP_LANDING <", value, "pickupLanding");
            return (Criteria) this;
        }

        public Criteria andPickupLandingLessThanOrEqualTo(Short value) {
            addCriterion("PICKUP_LANDING <=", value, "pickupLanding");
            return (Criteria) this;
        }

        public Criteria andPickupLandingIn(List<Short> values) {
            addCriterion("PICKUP_LANDING in", values, "pickupLanding");
            return (Criteria) this;
        }

        public Criteria andPickupLandingNotIn(List<Short> values) {
            addCriterion("PICKUP_LANDING not in", values, "pickupLanding");
            return (Criteria) this;
        }

        public Criteria andPickupLandingBetween(Short value1, Short value2) {
            addCriterion("PICKUP_LANDING between", value1, value2, "pickupLanding");
            return (Criteria) this;
        }

        public Criteria andPickupLandingNotBetween(Short value1, Short value2) {
            addCriterion("PICKUP_LANDING not between", value1, value2, "pickupLanding");
            return (Criteria) this;
        }

        public Criteria andSetdownLandingIsNull() {
            addCriterion("SETDOWN_LANDING is null");
            return (Criteria) this;
        }

        public Criteria andSetdownLandingIsNotNull() {
            addCriterion("SETDOWN_LANDING is not null");
            return (Criteria) this;
        }

        public Criteria andSetdownLandingEqualTo(Short value) {
            addCriterion("SETDOWN_LANDING =", value, "setdownLanding");
            return (Criteria) this;
        }

        public Criteria andSetdownLandingNotEqualTo(Short value) {
            addCriterion("SETDOWN_LANDING <>", value, "setdownLanding");
            return (Criteria) this;
        }

        public Criteria andSetdownLandingGreaterThan(Short value) {
            addCriterion("SETDOWN_LANDING >", value, "setdownLanding");
            return (Criteria) this;
        }

        public Criteria andSetdownLandingGreaterThanOrEqualTo(Short value) {
            addCriterion("SETDOWN_LANDING >=", value, "setdownLanding");
            return (Criteria) this;
        }

        public Criteria andSetdownLandingLessThan(Short value) {
            addCriterion("SETDOWN_LANDING <", value, "setdownLanding");
            return (Criteria) this;
        }

        public Criteria andSetdownLandingLessThanOrEqualTo(Short value) {
            addCriterion("SETDOWN_LANDING <=", value, "setdownLanding");
            return (Criteria) this;
        }

        public Criteria andSetdownLandingIn(List<Short> values) {
            addCriterion("SETDOWN_LANDING in", values, "setdownLanding");
            return (Criteria) this;
        }

        public Criteria andSetdownLandingNotIn(List<Short> values) {
            addCriterion("SETDOWN_LANDING not in", values, "setdownLanding");
            return (Criteria) this;
        }

        public Criteria andSetdownLandingBetween(Short value1, Short value2) {
            addCriterion("SETDOWN_LANDING between", value1, value2, "setdownLanding");
            return (Criteria) this;
        }

        public Criteria andSetdownLandingNotBetween(Short value1, Short value2) {
            addCriterion("SETDOWN_LANDING not between", value1, value2, "setdownLanding");
            return (Criteria) this;
        }

        public Criteria andRfidNoIsNull() {
            addCriterion("RFID_NO is null");
            return (Criteria) this;
        }

        public Criteria andRfidNoIsNotNull() {
            addCriterion("RFID_NO is not null");
            return (Criteria) this;
        }

        public Criteria andRfidNoEqualTo(String value) {
            addCriterion("RFID_NO =", value, "rfidNo");
            return (Criteria) this;
        }

        public Criteria andRfidNoNotEqualTo(String value) {
            addCriterion("RFID_NO <>", value, "rfidNo");
            return (Criteria) this;
        }

        public Criteria andRfidNoGreaterThan(String value) {
            addCriterion("RFID_NO >", value, "rfidNo");
            return (Criteria) this;
        }

        public Criteria andRfidNoGreaterThanOrEqualTo(String value) {
            addCriterion("RFID_NO >=", value, "rfidNo");
            return (Criteria) this;
        }

        public Criteria andRfidNoLessThan(String value) {
            addCriterion("RFID_NO <", value, "rfidNo");
            return (Criteria) this;
        }

        public Criteria andRfidNoLessThanOrEqualTo(String value) {
            addCriterion("RFID_NO <=", value, "rfidNo");
            return (Criteria) this;
        }

        public Criteria andRfidNoLike(String value) {
            addCriterion("RFID_NO like", value, "rfidNo");
            return (Criteria) this;
        }

        public Criteria andRfidNoNotLike(String value) {
            addCriterion("RFID_NO not like", value, "rfidNo");
            return (Criteria) this;
        }

        public Criteria andRfidNoIn(List<String> values) {
            addCriterion("RFID_NO in", values, "rfidNo");
            return (Criteria) this;
        }

        public Criteria andRfidNoNotIn(List<String> values) {
            addCriterion("RFID_NO not in", values, "rfidNo");
            return (Criteria) this;
        }

        public Criteria andRfidNoBetween(String value1, String value2) {
            addCriterion("RFID_NO between", value1, value2, "rfidNo");
            return (Criteria) this;
        }

        public Criteria andRfidNoNotBetween(String value1, String value2) {
            addCriterion("RFID_NO not between", value1, value2, "rfidNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoIsNull() {
            addCriterion("CNTR_NO is null");
            return (Criteria) this;
        }

        public Criteria andCntrNoIsNotNull() {
            addCriterion("CNTR_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCntrNoEqualTo(String value) {
            addCriterion("CNTR_NO =", value, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoNotEqualTo(String value) {
            addCriterion("CNTR_NO <>", value, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoGreaterThan(String value) {
            addCriterion("CNTR_NO >", value, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoGreaterThanOrEqualTo(String value) {
            addCriterion("CNTR_NO >=", value, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoLessThan(String value) {
            addCriterion("CNTR_NO <", value, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoLessThanOrEqualTo(String value) {
            addCriterion("CNTR_NO <=", value, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoLike(String value) {
            addCriterion("CNTR_NO like", value, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoNotLike(String value) {
            addCriterion("CNTR_NO not like", value, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoIn(List<String> values) {
            addCriterion("CNTR_NO in", values, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoNotIn(List<String> values) {
            addCriterion("CNTR_NO not in", values, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoBetween(String value1, String value2) {
            addCriterion("CNTR_NO between", value1, value2, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrNoNotBetween(String value1, String value2) {
            addCriterion("CNTR_NO not between", value1, value2, "cntrNo");
            return (Criteria) this;
        }

        public Criteria andCntrTypeIsNull() {
            addCriterion("CNTR_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCntrTypeIsNotNull() {
            addCriterion("CNTR_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCntrTypeEqualTo(String value) {
            addCriterion("CNTR_TYPE =", value, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeNotEqualTo(String value) {
            addCriterion("CNTR_TYPE <>", value, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeGreaterThan(String value) {
            addCriterion("CNTR_TYPE >", value, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CNTR_TYPE >=", value, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeLessThan(String value) {
            addCriterion("CNTR_TYPE <", value, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeLessThanOrEqualTo(String value) {
            addCriterion("CNTR_TYPE <=", value, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeLike(String value) {
            addCriterion("CNTR_TYPE like", value, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeNotLike(String value) {
            addCriterion("CNTR_TYPE not like", value, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeIn(List<String> values) {
            addCriterion("CNTR_TYPE in", values, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeNotIn(List<String> values) {
            addCriterion("CNTR_TYPE not in", values, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeBetween(String value1, String value2) {
            addCriterion("CNTR_TYPE between", value1, value2, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrTypeNotBetween(String value1, String value2) {
            addCriterion("CNTR_TYPE not between", value1, value2, "cntrType");
            return (Criteria) this;
        }

        public Criteria andCntrWeightIsNull() {
            addCriterion("CNTR_WEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andCntrWeightIsNotNull() {
            addCriterion("CNTR_WEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andCntrWeightEqualTo(Integer value) {
            addCriterion("CNTR_WEIGHT =", value, "cntrWeight");
            return (Criteria) this;
        }

        public Criteria andCntrWeightNotEqualTo(Integer value) {
            addCriterion("CNTR_WEIGHT <>", value, "cntrWeight");
            return (Criteria) this;
        }

        public Criteria andCntrWeightGreaterThan(Integer value) {
            addCriterion("CNTR_WEIGHT >", value, "cntrWeight");
            return (Criteria) this;
        }

        public Criteria andCntrWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("CNTR_WEIGHT >=", value, "cntrWeight");
            return (Criteria) this;
        }

        public Criteria andCntrWeightLessThan(Integer value) {
            addCriterion("CNTR_WEIGHT <", value, "cntrWeight");
            return (Criteria) this;
        }

        public Criteria andCntrWeightLessThanOrEqualTo(Integer value) {
            addCriterion("CNTR_WEIGHT <=", value, "cntrWeight");
            return (Criteria) this;
        }

        public Criteria andCntrWeightIn(List<Integer> values) {
            addCriterion("CNTR_WEIGHT in", values, "cntrWeight");
            return (Criteria) this;
        }

        public Criteria andCntrWeightNotIn(List<Integer> values) {
            addCriterion("CNTR_WEIGHT not in", values, "cntrWeight");
            return (Criteria) this;
        }

        public Criteria andCntrWeightBetween(Integer value1, Integer value2) {
            addCriterion("CNTR_WEIGHT between", value1, value2, "cntrWeight");
            return (Criteria) this;
        }

        public Criteria andCntrWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("CNTR_WEIGHT not between", value1, value2, "cntrWeight");
            return (Criteria) this;
        }

        public Criteria andJobEteTimeIsNull() {
            addCriterion("JOB_ETE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andJobEteTimeIsNotNull() {
            addCriterion("JOB_ETE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andJobEteTimeEqualTo(Integer value) {
            addCriterion("JOB_ETE_TIME =", value, "jobEteTime");
            return (Criteria) this;
        }

        public Criteria andJobEteTimeNotEqualTo(Integer value) {
            addCriterion("JOB_ETE_TIME <>", value, "jobEteTime");
            return (Criteria) this;
        }

        public Criteria andJobEteTimeGreaterThan(Integer value) {
            addCriterion("JOB_ETE_TIME >", value, "jobEteTime");
            return (Criteria) this;
        }

        public Criteria andJobEteTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("JOB_ETE_TIME >=", value, "jobEteTime");
            return (Criteria) this;
        }

        public Criteria andJobEteTimeLessThan(Integer value) {
            addCriterion("JOB_ETE_TIME <", value, "jobEteTime");
            return (Criteria) this;
        }

        public Criteria andJobEteTimeLessThanOrEqualTo(Integer value) {
            addCriterion("JOB_ETE_TIME <=", value, "jobEteTime");
            return (Criteria) this;
        }

        public Criteria andJobEteTimeIn(List<Integer> values) {
            addCriterion("JOB_ETE_TIME in", values, "jobEteTime");
            return (Criteria) this;
        }

        public Criteria andJobEteTimeNotIn(List<Integer> values) {
            addCriterion("JOB_ETE_TIME not in", values, "jobEteTime");
            return (Criteria) this;
        }

        public Criteria andJobEteTimeBetween(Integer value1, Integer value2) {
            addCriterion("JOB_ETE_TIME between", value1, value2, "jobEteTime");
            return (Criteria) this;
        }

        public Criteria andJobEteTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("JOB_ETE_TIME not between", value1, value2, "jobEteTime");
            return (Criteria) this;
        }

        public Criteria andJobAssignedTimeIsNull() {
            addCriterion("JOB_ASSIGNED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andJobAssignedTimeIsNotNull() {
            addCriterion("JOB_ASSIGNED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andJobAssignedTimeEqualTo(Date value) {
            addCriterion("JOB_ASSIGNED_TIME =", value, "jobAssignedTime");
            return (Criteria) this;
        }

        public Criteria andJobAssignedTimeNotEqualTo(Date value) {
            addCriterion("JOB_ASSIGNED_TIME <>", value, "jobAssignedTime");
            return (Criteria) this;
        }

        public Criteria andJobAssignedTimeGreaterThan(Date value) {
            addCriterion("JOB_ASSIGNED_TIME >", value, "jobAssignedTime");
            return (Criteria) this;
        }

        public Criteria andJobAssignedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("JOB_ASSIGNED_TIME >=", value, "jobAssignedTime");
            return (Criteria) this;
        }

        public Criteria andJobAssignedTimeLessThan(Date value) {
            addCriterion("JOB_ASSIGNED_TIME <", value, "jobAssignedTime");
            return (Criteria) this;
        }

        public Criteria andJobAssignedTimeLessThanOrEqualTo(Date value) {
            addCriterion("JOB_ASSIGNED_TIME <=", value, "jobAssignedTime");
            return (Criteria) this;
        }

        public Criteria andJobAssignedTimeIn(List<Date> values) {
            addCriterion("JOB_ASSIGNED_TIME in", values, "jobAssignedTime");
            return (Criteria) this;
        }

        public Criteria andJobAssignedTimeNotIn(List<Date> values) {
            addCriterion("JOB_ASSIGNED_TIME not in", values, "jobAssignedTime");
            return (Criteria) this;
        }

        public Criteria andJobAssignedTimeBetween(Date value1, Date value2) {
            addCriterion("JOB_ASSIGNED_TIME between", value1, value2, "jobAssignedTime");
            return (Criteria) this;
        }

        public Criteria andJobAssignedTimeNotBetween(Date value1, Date value2) {
            addCriterion("JOB_ASSIGNED_TIME not between", value1, value2, "jobAssignedTime");
            return (Criteria) this;
        }

        public Criteria andChassisArriIndIsNull() {
            addCriterion("CHASSIS_ARRI_IND is null");
            return (Criteria) this;
        }

        public Criteria andChassisArriIndIsNotNull() {
            addCriterion("CHASSIS_ARRI_IND is not null");
            return (Criteria) this;
        }

        public Criteria andChassisArriIndEqualTo(Short value) {
            addCriterion("CHASSIS_ARRI_IND =", value, "chassisArriInd");
            return (Criteria) this;
        }

        public Criteria andChassisArriIndNotEqualTo(Short value) {
            addCriterion("CHASSIS_ARRI_IND <>", value, "chassisArriInd");
            return (Criteria) this;
        }

        public Criteria andChassisArriIndGreaterThan(Short value) {
            addCriterion("CHASSIS_ARRI_IND >", value, "chassisArriInd");
            return (Criteria) this;
        }

        public Criteria andChassisArriIndGreaterThanOrEqualTo(Short value) {
            addCriterion("CHASSIS_ARRI_IND >=", value, "chassisArriInd");
            return (Criteria) this;
        }

        public Criteria andChassisArriIndLessThan(Short value) {
            addCriterion("CHASSIS_ARRI_IND <", value, "chassisArriInd");
            return (Criteria) this;
        }

        public Criteria andChassisArriIndLessThanOrEqualTo(Short value) {
            addCriterion("CHASSIS_ARRI_IND <=", value, "chassisArriInd");
            return (Criteria) this;
        }

        public Criteria andChassisArriIndIn(List<Short> values) {
            addCriterion("CHASSIS_ARRI_IND in", values, "chassisArriInd");
            return (Criteria) this;
        }

        public Criteria andChassisArriIndNotIn(List<Short> values) {
            addCriterion("CHASSIS_ARRI_IND not in", values, "chassisArriInd");
            return (Criteria) this;
        }

        public Criteria andChassisArriIndBetween(Short value1, Short value2) {
            addCriterion("CHASSIS_ARRI_IND between", value1, value2, "chassisArriInd");
            return (Criteria) this;
        }

        public Criteria andChassisArriIndNotBetween(Short value1, Short value2) {
            addCriterion("CHASSIS_ARRI_IND not between", value1, value2, "chassisArriInd");
            return (Criteria) this;
        }

        public Criteria andChassisArriTimeoutIsNull() {
            addCriterion("CHASSIS_ARRI_TIMEOUT is null");
            return (Criteria) this;
        }

        public Criteria andChassisArriTimeoutIsNotNull() {
            addCriterion("CHASSIS_ARRI_TIMEOUT is not null");
            return (Criteria) this;
        }

        public Criteria andChassisArriTimeoutEqualTo(Short value) {
            addCriterion("CHASSIS_ARRI_TIMEOUT =", value, "chassisArriTimeout");
            return (Criteria) this;
        }

        public Criteria andChassisArriTimeoutNotEqualTo(Short value) {
            addCriterion("CHASSIS_ARRI_TIMEOUT <>", value, "chassisArriTimeout");
            return (Criteria) this;
        }

        public Criteria andChassisArriTimeoutGreaterThan(Short value) {
            addCriterion("CHASSIS_ARRI_TIMEOUT >", value, "chassisArriTimeout");
            return (Criteria) this;
        }

        public Criteria andChassisArriTimeoutGreaterThanOrEqualTo(Short value) {
            addCriterion("CHASSIS_ARRI_TIMEOUT >=", value, "chassisArriTimeout");
            return (Criteria) this;
        }

        public Criteria andChassisArriTimeoutLessThan(Short value) {
            addCriterion("CHASSIS_ARRI_TIMEOUT <", value, "chassisArriTimeout");
            return (Criteria) this;
        }

        public Criteria andChassisArriTimeoutLessThanOrEqualTo(Short value) {
            addCriterion("CHASSIS_ARRI_TIMEOUT <=", value, "chassisArriTimeout");
            return (Criteria) this;
        }

        public Criteria andChassisArriTimeoutIn(List<Short> values) {
            addCriterion("CHASSIS_ARRI_TIMEOUT in", values, "chassisArriTimeout");
            return (Criteria) this;
        }

        public Criteria andChassisArriTimeoutNotIn(List<Short> values) {
            addCriterion("CHASSIS_ARRI_TIMEOUT not in", values, "chassisArriTimeout");
            return (Criteria) this;
        }

        public Criteria andChassisArriTimeoutBetween(Short value1, Short value2) {
            addCriterion("CHASSIS_ARRI_TIMEOUT between", value1, value2, "chassisArriTimeout");
            return (Criteria) this;
        }

        public Criteria andChassisArriTimeoutNotBetween(Short value1, Short value2) {
            addCriterion("CHASSIS_ARRI_TIMEOUT not between", value1, value2, "chassisArriTimeout");
            return (Criteria) this;
        }

        public Criteria andPickupIndIsNull() {
            addCriterion("PICKUP_IND is null");
            return (Criteria) this;
        }

        public Criteria andPickupIndIsNotNull() {
            addCriterion("PICKUP_IND is not null");
            return (Criteria) this;
        }

        public Criteria andPickupIndEqualTo(String value) {
            addCriterion("PICKUP_IND =", value, "pickupInd");
            return (Criteria) this;
        }

        public Criteria andPickupIndNotEqualTo(String value) {
            addCriterion("PICKUP_IND <>", value, "pickupInd");
            return (Criteria) this;
        }

        public Criteria andPickupIndGreaterThan(String value) {
            addCriterion("PICKUP_IND >", value, "pickupInd");
            return (Criteria) this;
        }

        public Criteria andPickupIndGreaterThanOrEqualTo(String value) {
            addCriterion("PICKUP_IND >=", value, "pickupInd");
            return (Criteria) this;
        }

        public Criteria andPickupIndLessThan(String value) {
            addCriterion("PICKUP_IND <", value, "pickupInd");
            return (Criteria) this;
        }

        public Criteria andPickupIndLessThanOrEqualTo(String value) {
            addCriterion("PICKUP_IND <=", value, "pickupInd");
            return (Criteria) this;
        }

        public Criteria andPickupIndLike(String value) {
            addCriterion("PICKUP_IND like", value, "pickupInd");
            return (Criteria) this;
        }

        public Criteria andPickupIndNotLike(String value) {
            addCriterion("PICKUP_IND not like", value, "pickupInd");
            return (Criteria) this;
        }

        public Criteria andPickupIndIn(List<String> values) {
            addCriterion("PICKUP_IND in", values, "pickupInd");
            return (Criteria) this;
        }

        public Criteria andPickupIndNotIn(List<String> values) {
            addCriterion("PICKUP_IND not in", values, "pickupInd");
            return (Criteria) this;
        }

        public Criteria andPickupIndBetween(String value1, String value2) {
            addCriterion("PICKUP_IND between", value1, value2, "pickupInd");
            return (Criteria) this;
        }

        public Criteria andPickupIndNotBetween(String value1, String value2) {
            addCriterion("PICKUP_IND not between", value1, value2, "pickupInd");
            return (Criteria) this;
        }

        public Criteria andPickupTimeIsNull() {
            addCriterion("PICKUP_TIME is null");
            return (Criteria) this;
        }

        public Criteria andPickupTimeIsNotNull() {
            addCriterion("PICKUP_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andPickupTimeEqualTo(Date value) {
            addCriterion("PICKUP_TIME =", value, "pickupTime");
            return (Criteria) this;
        }

        public Criteria andPickupTimeNotEqualTo(Date value) {
            addCriterion("PICKUP_TIME <>", value, "pickupTime");
            return (Criteria) this;
        }

        public Criteria andPickupTimeGreaterThan(Date value) {
            addCriterion("PICKUP_TIME >", value, "pickupTime");
            return (Criteria) this;
        }

        public Criteria andPickupTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("PICKUP_TIME >=", value, "pickupTime");
            return (Criteria) this;
        }

        public Criteria andPickupTimeLessThan(Date value) {
            addCriterion("PICKUP_TIME <", value, "pickupTime");
            return (Criteria) this;
        }

        public Criteria andPickupTimeLessThanOrEqualTo(Date value) {
            addCriterion("PICKUP_TIME <=", value, "pickupTime");
            return (Criteria) this;
        }

        public Criteria andPickupTimeIn(List<Date> values) {
            addCriterion("PICKUP_TIME in", values, "pickupTime");
            return (Criteria) this;
        }

        public Criteria andPickupTimeNotIn(List<Date> values) {
            addCriterion("PICKUP_TIME not in", values, "pickupTime");
            return (Criteria) this;
        }

        public Criteria andPickupTimeBetween(Date value1, Date value2) {
            addCriterion("PICKUP_TIME between", value1, value2, "pickupTime");
            return (Criteria) this;
        }

        public Criteria andPickupTimeNotBetween(Date value1, Date value2) {
            addCriterion("PICKUP_TIME not between", value1, value2, "pickupTime");
            return (Criteria) this;
        }

        public Criteria andJobFinishIndIsNull() {
            addCriterion("JOB_FINISH_IND is null");
            return (Criteria) this;
        }

        public Criteria andJobFinishIndIsNotNull() {
            addCriterion("JOB_FINISH_IND is not null");
            return (Criteria) this;
        }

        public Criteria andJobFinishIndEqualTo(String value) {
            addCriterion("JOB_FINISH_IND =", value, "jobFinishInd");
            return (Criteria) this;
        }

        public Criteria andJobFinishIndNotEqualTo(String value) {
            addCriterion("JOB_FINISH_IND <>", value, "jobFinishInd");
            return (Criteria) this;
        }

        public Criteria andJobFinishIndGreaterThan(String value) {
            addCriterion("JOB_FINISH_IND >", value, "jobFinishInd");
            return (Criteria) this;
        }

        public Criteria andJobFinishIndGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_FINISH_IND >=", value, "jobFinishInd");
            return (Criteria) this;
        }

        public Criteria andJobFinishIndLessThan(String value) {
            addCriterion("JOB_FINISH_IND <", value, "jobFinishInd");
            return (Criteria) this;
        }

        public Criteria andJobFinishIndLessThanOrEqualTo(String value) {
            addCriterion("JOB_FINISH_IND <=", value, "jobFinishInd");
            return (Criteria) this;
        }

        public Criteria andJobFinishIndLike(String value) {
            addCriterion("JOB_FINISH_IND like", value, "jobFinishInd");
            return (Criteria) this;
        }

        public Criteria andJobFinishIndNotLike(String value) {
            addCriterion("JOB_FINISH_IND not like", value, "jobFinishInd");
            return (Criteria) this;
        }

        public Criteria andJobFinishIndIn(List<String> values) {
            addCriterion("JOB_FINISH_IND in", values, "jobFinishInd");
            return (Criteria) this;
        }

        public Criteria andJobFinishIndNotIn(List<String> values) {
            addCriterion("JOB_FINISH_IND not in", values, "jobFinishInd");
            return (Criteria) this;
        }

        public Criteria andJobFinishIndBetween(String value1, String value2) {
            addCriterion("JOB_FINISH_IND between", value1, value2, "jobFinishInd");
            return (Criteria) this;
        }

        public Criteria andJobFinishIndNotBetween(String value1, String value2) {
            addCriterion("JOB_FINISH_IND not between", value1, value2, "jobFinishInd");
            return (Criteria) this;
        }

        public Criteria andJobFinishTimeIsNull() {
            addCriterion("JOB_FINISH_TIME is null");
            return (Criteria) this;
        }

        public Criteria andJobFinishTimeIsNotNull() {
            addCriterion("JOB_FINISH_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andJobFinishTimeEqualTo(Date value) {
            addCriterion("JOB_FINISH_TIME =", value, "jobFinishTime");
            return (Criteria) this;
        }

        public Criteria andJobFinishTimeNotEqualTo(Date value) {
            addCriterion("JOB_FINISH_TIME <>", value, "jobFinishTime");
            return (Criteria) this;
        }

        public Criteria andJobFinishTimeGreaterThan(Date value) {
            addCriterion("JOB_FINISH_TIME >", value, "jobFinishTime");
            return (Criteria) this;
        }

        public Criteria andJobFinishTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("JOB_FINISH_TIME >=", value, "jobFinishTime");
            return (Criteria) this;
        }

        public Criteria andJobFinishTimeLessThan(Date value) {
            addCriterion("JOB_FINISH_TIME <", value, "jobFinishTime");
            return (Criteria) this;
        }

        public Criteria andJobFinishTimeLessThanOrEqualTo(Date value) {
            addCriterion("JOB_FINISH_TIME <=", value, "jobFinishTime");
            return (Criteria) this;
        }

        public Criteria andJobFinishTimeIn(List<Date> values) {
            addCriterion("JOB_FINISH_TIME in", values, "jobFinishTime");
            return (Criteria) this;
        }

        public Criteria andJobFinishTimeNotIn(List<Date> values) {
            addCriterion("JOB_FINISH_TIME not in", values, "jobFinishTime");
            return (Criteria) this;
        }

        public Criteria andJobFinishTimeBetween(Date value1, Date value2) {
            addCriterion("JOB_FINISH_TIME between", value1, value2, "jobFinishTime");
            return (Criteria) this;
        }

        public Criteria andJobFinishTimeNotBetween(Date value1, Date value2) {
            addCriterion("JOB_FINISH_TIME not between", value1, value2, "jobFinishTime");
            return (Criteria) this;
        }

        public Criteria andTimeElapsedIsNull() {
            addCriterion("TIME_ELAPSED is null");
            return (Criteria) this;
        }

        public Criteria andTimeElapsedIsNotNull() {
            addCriterion("TIME_ELAPSED is not null");
            return (Criteria) this;
        }

        public Criteria andTimeElapsedEqualTo(Integer value) {
            addCriterion("TIME_ELAPSED =", value, "timeElapsed");
            return (Criteria) this;
        }

        public Criteria andTimeElapsedNotEqualTo(Integer value) {
            addCriterion("TIME_ELAPSED <>", value, "timeElapsed");
            return (Criteria) this;
        }

        public Criteria andTimeElapsedGreaterThan(Integer value) {
            addCriterion("TIME_ELAPSED >", value, "timeElapsed");
            return (Criteria) this;
        }

        public Criteria andTimeElapsedGreaterThanOrEqualTo(Integer value) {
            addCriterion("TIME_ELAPSED >=", value, "timeElapsed");
            return (Criteria) this;
        }

        public Criteria andTimeElapsedLessThan(Integer value) {
            addCriterion("TIME_ELAPSED <", value, "timeElapsed");
            return (Criteria) this;
        }

        public Criteria andTimeElapsedLessThanOrEqualTo(Integer value) {
            addCriterion("TIME_ELAPSED <=", value, "timeElapsed");
            return (Criteria) this;
        }

        public Criteria andTimeElapsedIn(List<Integer> values) {
            addCriterion("TIME_ELAPSED in", values, "timeElapsed");
            return (Criteria) this;
        }

        public Criteria andTimeElapsedNotIn(List<Integer> values) {
            addCriterion("TIME_ELAPSED not in", values, "timeElapsed");
            return (Criteria) this;
        }

        public Criteria andTimeElapsedBetween(Integer value1, Integer value2) {
            addCriterion("TIME_ELAPSED between", value1, value2, "timeElapsed");
            return (Criteria) this;
        }

        public Criteria andTimeElapsedNotBetween(Integer value1, Integer value2) {
            addCriterion("TIME_ELAPSED not between", value1, value2, "timeElapsed");
            return (Criteria) this;
        }

        public Criteria andErrorCodeIsNull() {
            addCriterion("ERROR_CODE is null");
            return (Criteria) this;
        }

        public Criteria andErrorCodeIsNotNull() {
            addCriterion("ERROR_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andErrorCodeEqualTo(Integer value) {
            addCriterion("ERROR_CODE =", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeNotEqualTo(Integer value) {
            addCriterion("ERROR_CODE <>", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeGreaterThan(Integer value) {
            addCriterion("ERROR_CODE >", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ERROR_CODE >=", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeLessThan(Integer value) {
            addCriterion("ERROR_CODE <", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeLessThanOrEqualTo(Integer value) {
            addCriterion("ERROR_CODE <=", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeIn(List<Integer> values) {
            addCriterion("ERROR_CODE in", values, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeNotIn(List<Integer> values) {
            addCriterion("ERROR_CODE not in", values, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeBetween(Integer value1, Integer value2) {
            addCriterion("ERROR_CODE between", value1, value2, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("ERROR_CODE not between", value1, value2, "errorCode");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("MODIFY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("MODIFY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("MODIFY_DATE =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("MODIFY_DATE <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("MODIFY_DATE >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("MODIFY_DATE <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("MODIFY_DATE in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("MODIFY_DATE not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNull() {
            addCriterion("MODIFY_USER is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNotNull() {
            addCriterion("MODIFY_USER is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserEqualTo(String value) {
            addCriterion("MODIFY_USER =", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotEqualTo(String value) {
            addCriterion("MODIFY_USER <>", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThan(String value) {
            addCriterion("MODIFY_USER >", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFY_USER >=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThan(String value) {
            addCriterion("MODIFY_USER <", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThanOrEqualTo(String value) {
            addCriterion("MODIFY_USER <=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLike(String value) {
            addCriterion("MODIFY_USER like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotLike(String value) {
            addCriterion("MODIFY_USER not like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIn(List<String> values) {
            addCriterion("MODIFY_USER in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotIn(List<String> values) {
            addCriterion("MODIFY_USER not in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserBetween(String value1, String value2) {
            addCriterion("MODIFY_USER between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotBetween(String value1, String value2) {
            addCriterion("MODIFY_USER not between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andRfidNoActualIsNull() {
            addCriterion("RFID_NO_ACTUAL is null");
            return (Criteria) this;
        }

        public Criteria andRfidNoActualIsNotNull() {
            addCriterion("RFID_NO_ACTUAL is not null");
            return (Criteria) this;
        }

        public Criteria andRfidNoActualEqualTo(String value) {
            addCriterion("RFID_NO_ACTUAL =", value, "rfidNoActual");
            return (Criteria) this;
        }

        public Criteria andRfidNoActualNotEqualTo(String value) {
            addCriterion("RFID_NO_ACTUAL <>", value, "rfidNoActual");
            return (Criteria) this;
        }

        public Criteria andRfidNoActualGreaterThan(String value) {
            addCriterion("RFID_NO_ACTUAL >", value, "rfidNoActual");
            return (Criteria) this;
        }

        public Criteria andRfidNoActualGreaterThanOrEqualTo(String value) {
            addCriterion("RFID_NO_ACTUAL >=", value, "rfidNoActual");
            return (Criteria) this;
        }

        public Criteria andRfidNoActualLessThan(String value) {
            addCriterion("RFID_NO_ACTUAL <", value, "rfidNoActual");
            return (Criteria) this;
        }

        public Criteria andRfidNoActualLessThanOrEqualTo(String value) {
            addCriterion("RFID_NO_ACTUAL <=", value, "rfidNoActual");
            return (Criteria) this;
        }

        public Criteria andRfidNoActualLike(String value) {
            addCriterion("RFID_NO_ACTUAL like", value, "rfidNoActual");
            return (Criteria) this;
        }

        public Criteria andRfidNoActualNotLike(String value) {
            addCriterion("RFID_NO_ACTUAL not like", value, "rfidNoActual");
            return (Criteria) this;
        }

        public Criteria andRfidNoActualIn(List<String> values) {
            addCriterion("RFID_NO_ACTUAL in", values, "rfidNoActual");
            return (Criteria) this;
        }

        public Criteria andRfidNoActualNotIn(List<String> values) {
            addCriterion("RFID_NO_ACTUAL not in", values, "rfidNoActual");
            return (Criteria) this;
        }

        public Criteria andRfidNoActualBetween(String value1, String value2) {
            addCriterion("RFID_NO_ACTUAL between", value1, value2, "rfidNoActual");
            return (Criteria) this;
        }

        public Criteria andRfidNoActualNotBetween(String value1, String value2) {
            addCriterion("RFID_NO_ACTUAL not between", value1, value2, "rfidNoActual");
            return (Criteria) this;
        }

        public Criteria andJobCreateTimeIsNull() {
            addCriterion("JOB_CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andJobCreateTimeIsNotNull() {
            addCriterion("JOB_CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andJobCreateTimeEqualTo(Date value) {
            addCriterion("JOB_CREATE_TIME =", value, "jobCreateTime");
            return (Criteria) this;
        }

        public Criteria andJobCreateTimeNotEqualTo(Date value) {
            addCriterion("JOB_CREATE_TIME <>", value, "jobCreateTime");
            return (Criteria) this;
        }

        public Criteria andJobCreateTimeGreaterThan(Date value) {
            addCriterion("JOB_CREATE_TIME >", value, "jobCreateTime");
            return (Criteria) this;
        }

        public Criteria andJobCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("JOB_CREATE_TIME >=", value, "jobCreateTime");
            return (Criteria) this;
        }

        public Criteria andJobCreateTimeLessThan(Date value) {
            addCriterion("JOB_CREATE_TIME <", value, "jobCreateTime");
            return (Criteria) this;
        }

        public Criteria andJobCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("JOB_CREATE_TIME <=", value, "jobCreateTime");
            return (Criteria) this;
        }

        public Criteria andJobCreateTimeIn(List<Date> values) {
            addCriterion("JOB_CREATE_TIME in", values, "jobCreateTime");
            return (Criteria) this;
        }

        public Criteria andJobCreateTimeNotIn(List<Date> values) {
            addCriterion("JOB_CREATE_TIME not in", values, "jobCreateTime");
            return (Criteria) this;
        }

        public Criteria andJobCreateTimeBetween(Date value1, Date value2) {
            addCriterion("JOB_CREATE_TIME between", value1, value2, "jobCreateTime");
            return (Criteria) this;
        }

        public Criteria andJobCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("JOB_CREATE_TIME not between", value1, value2, "jobCreateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ARMGJOBQ
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}