package com.example.dao.entity;

import java.util.Date;

public class Armgslottos extends ArmgslottosKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTTOS.CNTR_NO
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    private String cntrNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTTOS.CNTR_TYPE
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    private String cntrType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTTOS.CNTR_WEIGHT
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    private Integer cntrWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTTOS.DOOR_DIRECT
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    private Short doorDirect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTTOS.CREATE_DATE
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTTOS.CREATE_USER
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTTOS.MODIFY_DATE
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTTOS.MODIFY_USER
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    private String modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTTOS.STATUS
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGSLOTTOS.ERROR_CODE
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    private Integer errorCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTTOS.CNTR_NO
     *
     * @return the value of ARMGSLOTTOS.CNTR_NO
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public String getCntrNo() {
        return cntrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTTOS.CNTR_NO
     *
     * @param cntrNo the value for ARMGSLOTTOS.CNTR_NO
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public void setCntrNo(String cntrNo) {
        this.cntrNo = cntrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTTOS.CNTR_TYPE
     *
     * @return the value of ARMGSLOTTOS.CNTR_TYPE
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public String getCntrType() {
        return cntrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTTOS.CNTR_TYPE
     *
     * @param cntrType the value for ARMGSLOTTOS.CNTR_TYPE
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public void setCntrType(String cntrType) {
        this.cntrType = cntrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTTOS.CNTR_WEIGHT
     *
     * @return the value of ARMGSLOTTOS.CNTR_WEIGHT
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public Integer getCntrWeight() {
        return cntrWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTTOS.CNTR_WEIGHT
     *
     * @param cntrWeight the value for ARMGSLOTTOS.CNTR_WEIGHT
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public void setCntrWeight(Integer cntrWeight) {
        this.cntrWeight = cntrWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTTOS.DOOR_DIRECT
     *
     * @return the value of ARMGSLOTTOS.DOOR_DIRECT
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public Short getDoorDirect() {
        return doorDirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTTOS.DOOR_DIRECT
     *
     * @param doorDirect the value for ARMGSLOTTOS.DOOR_DIRECT
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public void setDoorDirect(Short doorDirect) {
        this.doorDirect = doorDirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTTOS.CREATE_DATE
     *
     * @return the value of ARMGSLOTTOS.CREATE_DATE
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTTOS.CREATE_DATE
     *
     * @param createDate the value for ARMGSLOTTOS.CREATE_DATE
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTTOS.CREATE_USER
     *
     * @return the value of ARMGSLOTTOS.CREATE_USER
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTTOS.CREATE_USER
     *
     * @param createUser the value for ARMGSLOTTOS.CREATE_USER
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTTOS.MODIFY_DATE
     *
     * @return the value of ARMGSLOTTOS.MODIFY_DATE
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTTOS.MODIFY_DATE
     *
     * @param modifyDate the value for ARMGSLOTTOS.MODIFY_DATE
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTTOS.MODIFY_USER
     *
     * @return the value of ARMGSLOTTOS.MODIFY_USER
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTTOS.MODIFY_USER
     *
     * @param modifyUser the value for ARMGSLOTTOS.MODIFY_USER
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTTOS.STATUS
     *
     * @return the value of ARMGSLOTTOS.STATUS
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTTOS.STATUS
     *
     * @param status the value for ARMGSLOTTOS.STATUS
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGSLOTTOS.ERROR_CODE
     *
     * @return the value of ARMGSLOTTOS.ERROR_CODE
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public Integer getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGSLOTTOS.ERROR_CODE
     *
     * @param errorCode the value for ARMGSLOTTOS.ERROR_CODE
     *
     * @mbg.generated Sat Oct 27 16:56:27 GMT+08:00 2018
     */
    public void setErrorCode(Integer errorCode) {
        this.errorCode = errorCode;
    }
}