package com.example.dao.entity;

import java.util.Date;

public class Armgjobq {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.JOB_ORDER_SEQ_MS
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Long jobOrderSeqMs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.JOB_ORDER_SEQ_DT
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Short jobOrderSeqDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.JOB_STATUS_QFR
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private String jobStatusQfr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.JOB_MOTION_QFR
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private String jobMotionQfr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.PRIORITY_WEIGHT
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Integer priorityWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.ARMG_ID
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private String armgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.WHO_ASSIGN
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private String whoAssign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.BLOCK_FROM
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private String blockFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.BAY_FROM
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Short bayFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.ROW_FROM
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Short rowFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.TIER_FROM
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Short tierFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.DOOR_DIR_FROM
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Short doorDirFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.BLOCK_TO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private String blockTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.BAY_TO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Short bayTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.ROW_TO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Short rowTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.TIER_TO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Short tierTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.DOOR_DIR_TO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Short doorDirTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.CHASSIS_TYPE
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Short chassisType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.CHASSIS_NO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Integer chassisNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.POS_ON_CHASSIS
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Short posOnChassis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.PICKUP_LANDING
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Short pickupLanding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.SETDOWN_LANDING
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Short setdownLanding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.RFID_NO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private String rfidNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.CNTR_NO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private String cntrNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.CNTR_TYPE
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private String cntrType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.CNTR_WEIGHT
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Integer cntrWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.JOB_ETE_TIME
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Integer jobEteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.JOB_ASSIGNED_TIME
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Date jobAssignedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.CHASSIS_ARRI_IND
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Short chassisArriInd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.CHASSIS_ARRI_TIMEOUT
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Short chassisArriTimeout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.PICKUP_IND
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private String pickupInd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.PICKUP_TIME
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Date pickupTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.JOB_FINISH_IND
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private String jobFinishInd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.JOB_FINISH_TIME
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Date jobFinishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.TIME_ELAPSED
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Integer timeElapsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.ERROR_CODE
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Integer errorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.MODIFY_DATE
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.MODIFY_USER
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private String modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.RFID_NO_ACTUAL
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private String rfidNoActual;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMGJOBQ.JOB_CREATE_TIME
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    private Date jobCreateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.JOB_ORDER_SEQ_MS
     *
     * @return the value of ARMGJOBQ.JOB_ORDER_SEQ_MS
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Long getJobOrderSeqMs() {
        return jobOrderSeqMs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.JOB_ORDER_SEQ_MS
     *
     * @param jobOrderSeqMs the value for ARMGJOBQ.JOB_ORDER_SEQ_MS
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setJobOrderSeqMs(Long jobOrderSeqMs) {
        this.jobOrderSeqMs = jobOrderSeqMs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.JOB_ORDER_SEQ_DT
     *
     * @return the value of ARMGJOBQ.JOB_ORDER_SEQ_DT
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Short getJobOrderSeqDt() {
        return jobOrderSeqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.JOB_ORDER_SEQ_DT
     *
     * @param jobOrderSeqDt the value for ARMGJOBQ.JOB_ORDER_SEQ_DT
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setJobOrderSeqDt(Short jobOrderSeqDt) {
        this.jobOrderSeqDt = jobOrderSeqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.JOB_STATUS_QFR
     *
     * @return the value of ARMGJOBQ.JOB_STATUS_QFR
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public String getJobStatusQfr() {
        return jobStatusQfr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.JOB_STATUS_QFR
     *
     * @param jobStatusQfr the value for ARMGJOBQ.JOB_STATUS_QFR
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setJobStatusQfr(String jobStatusQfr) {
        this.jobStatusQfr = jobStatusQfr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.JOB_MOTION_QFR
     *
     * @return the value of ARMGJOBQ.JOB_MOTION_QFR
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public String getJobMotionQfr() {
        return jobMotionQfr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.JOB_MOTION_QFR
     *
     * @param jobMotionQfr the value for ARMGJOBQ.JOB_MOTION_QFR
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setJobMotionQfr(String jobMotionQfr) {
        this.jobMotionQfr = jobMotionQfr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.PRIORITY_WEIGHT
     *
     * @return the value of ARMGJOBQ.PRIORITY_WEIGHT
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Integer getPriorityWeight() {
        return priorityWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.PRIORITY_WEIGHT
     *
     * @param priorityWeight the value for ARMGJOBQ.PRIORITY_WEIGHT
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setPriorityWeight(Integer priorityWeight) {
        this.priorityWeight = priorityWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.ARMG_ID
     *
     * @return the value of ARMGJOBQ.ARMG_ID
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public String getArmgId() {
        return armgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.ARMG_ID
     *
     * @param armgId the value for ARMGJOBQ.ARMG_ID
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setArmgId(String armgId) {
        this.armgId = armgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.WHO_ASSIGN
     *
     * @return the value of ARMGJOBQ.WHO_ASSIGN
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public String getWhoAssign() {
        return whoAssign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.WHO_ASSIGN
     *
     * @param whoAssign the value for ARMGJOBQ.WHO_ASSIGN
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setWhoAssign(String whoAssign) {
        this.whoAssign = whoAssign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.BLOCK_FROM
     *
     * @return the value of ARMGJOBQ.BLOCK_FROM
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public String getBlockFrom() {
        return blockFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.BLOCK_FROM
     *
     * @param blockFrom the value for ARMGJOBQ.BLOCK_FROM
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setBlockFrom(String blockFrom) {
        this.blockFrom = blockFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.BAY_FROM
     *
     * @return the value of ARMGJOBQ.BAY_FROM
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Short getBayFrom() {
        return bayFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.BAY_FROM
     *
     * @param bayFrom the value for ARMGJOBQ.BAY_FROM
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setBayFrom(Short bayFrom) {
        this.bayFrom = bayFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.ROW_FROM
     *
     * @return the value of ARMGJOBQ.ROW_FROM
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Short getRowFrom() {
        return rowFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.ROW_FROM
     *
     * @param rowFrom the value for ARMGJOBQ.ROW_FROM
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setRowFrom(Short rowFrom) {
        this.rowFrom = rowFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.TIER_FROM
     *
     * @return the value of ARMGJOBQ.TIER_FROM
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Short getTierFrom() {
        return tierFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.TIER_FROM
     *
     * @param tierFrom the value for ARMGJOBQ.TIER_FROM
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setTierFrom(Short tierFrom) {
        this.tierFrom = tierFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.DOOR_DIR_FROM
     *
     * @return the value of ARMGJOBQ.DOOR_DIR_FROM
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Short getDoorDirFrom() {
        return doorDirFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.DOOR_DIR_FROM
     *
     * @param doorDirFrom the value for ARMGJOBQ.DOOR_DIR_FROM
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setDoorDirFrom(Short doorDirFrom) {
        this.doorDirFrom = doorDirFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.BLOCK_TO
     *
     * @return the value of ARMGJOBQ.BLOCK_TO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public String getBlockTo() {
        return blockTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.BLOCK_TO
     *
     * @param blockTo the value for ARMGJOBQ.BLOCK_TO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setBlockTo(String blockTo) {
        this.blockTo = blockTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.BAY_TO
     *
     * @return the value of ARMGJOBQ.BAY_TO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Short getBayTo() {
        return bayTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.BAY_TO
     *
     * @param bayTo the value for ARMGJOBQ.BAY_TO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setBayTo(Short bayTo) {
        this.bayTo = bayTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.ROW_TO
     *
     * @return the value of ARMGJOBQ.ROW_TO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Short getRowTo() {
        return rowTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.ROW_TO
     *
     * @param rowTo the value for ARMGJOBQ.ROW_TO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setRowTo(Short rowTo) {
        this.rowTo = rowTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.TIER_TO
     *
     * @return the value of ARMGJOBQ.TIER_TO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Short getTierTo() {
        return tierTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.TIER_TO
     *
     * @param tierTo the value for ARMGJOBQ.TIER_TO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setTierTo(Short tierTo) {
        this.tierTo = tierTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.DOOR_DIR_TO
     *
     * @return the value of ARMGJOBQ.DOOR_DIR_TO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Short getDoorDirTo() {
        return doorDirTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.DOOR_DIR_TO
     *
     * @param doorDirTo the value for ARMGJOBQ.DOOR_DIR_TO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setDoorDirTo(Short doorDirTo) {
        this.doorDirTo = doorDirTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.CHASSIS_TYPE
     *
     * @return the value of ARMGJOBQ.CHASSIS_TYPE
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Short getChassisType() {
        return chassisType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.CHASSIS_TYPE
     *
     * @param chassisType the value for ARMGJOBQ.CHASSIS_TYPE
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setChassisType(Short chassisType) {
        this.chassisType = chassisType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.CHASSIS_NO
     *
     * @return the value of ARMGJOBQ.CHASSIS_NO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Integer getChassisNo() {
        return chassisNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.CHASSIS_NO
     *
     * @param chassisNo the value for ARMGJOBQ.CHASSIS_NO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setChassisNo(Integer chassisNo) {
        this.chassisNo = chassisNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.POS_ON_CHASSIS
     *
     * @return the value of ARMGJOBQ.POS_ON_CHASSIS
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Short getPosOnChassis() {
        return posOnChassis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.POS_ON_CHASSIS
     *
     * @param posOnChassis the value for ARMGJOBQ.POS_ON_CHASSIS
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setPosOnChassis(Short posOnChassis) {
        this.posOnChassis = posOnChassis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.PICKUP_LANDING
     *
     * @return the value of ARMGJOBQ.PICKUP_LANDING
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Short getPickupLanding() {
        return pickupLanding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.PICKUP_LANDING
     *
     * @param pickupLanding the value for ARMGJOBQ.PICKUP_LANDING
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setPickupLanding(Short pickupLanding) {
        this.pickupLanding = pickupLanding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.SETDOWN_LANDING
     *
     * @return the value of ARMGJOBQ.SETDOWN_LANDING
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Short getSetdownLanding() {
        return setdownLanding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.SETDOWN_LANDING
     *
     * @param setdownLanding the value for ARMGJOBQ.SETDOWN_LANDING
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setSetdownLanding(Short setdownLanding) {
        this.setdownLanding = setdownLanding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.RFID_NO
     *
     * @return the value of ARMGJOBQ.RFID_NO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public String getRfidNo() {
        return rfidNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.RFID_NO
     *
     * @param rfidNo the value for ARMGJOBQ.RFID_NO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setRfidNo(String rfidNo) {
        this.rfidNo = rfidNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.CNTR_NO
     *
     * @return the value of ARMGJOBQ.CNTR_NO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public String getCntrNo() {
        return cntrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.CNTR_NO
     *
     * @param cntrNo the value for ARMGJOBQ.CNTR_NO
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setCntrNo(String cntrNo) {
        this.cntrNo = cntrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.CNTR_TYPE
     *
     * @return the value of ARMGJOBQ.CNTR_TYPE
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public String getCntrType() {
        return cntrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.CNTR_TYPE
     *
     * @param cntrType the value for ARMGJOBQ.CNTR_TYPE
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setCntrType(String cntrType) {
        this.cntrType = cntrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.CNTR_WEIGHT
     *
     * @return the value of ARMGJOBQ.CNTR_WEIGHT
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Integer getCntrWeight() {
        return cntrWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.CNTR_WEIGHT
     *
     * @param cntrWeight the value for ARMGJOBQ.CNTR_WEIGHT
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setCntrWeight(Integer cntrWeight) {
        this.cntrWeight = cntrWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.JOB_ETE_TIME
     *
     * @return the value of ARMGJOBQ.JOB_ETE_TIME
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Integer getJobEteTime() {
        return jobEteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.JOB_ETE_TIME
     *
     * @param jobEteTime the value for ARMGJOBQ.JOB_ETE_TIME
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setJobEteTime(Integer jobEteTime) {
        this.jobEteTime = jobEteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.JOB_ASSIGNED_TIME
     *
     * @return the value of ARMGJOBQ.JOB_ASSIGNED_TIME
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Date getJobAssignedTime() {
        return jobAssignedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.JOB_ASSIGNED_TIME
     *
     * @param jobAssignedTime the value for ARMGJOBQ.JOB_ASSIGNED_TIME
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setJobAssignedTime(Date jobAssignedTime) {
        this.jobAssignedTime = jobAssignedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.CHASSIS_ARRI_IND
     *
     * @return the value of ARMGJOBQ.CHASSIS_ARRI_IND
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Short getChassisArriInd() {
        return chassisArriInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.CHASSIS_ARRI_IND
     *
     * @param chassisArriInd the value for ARMGJOBQ.CHASSIS_ARRI_IND
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setChassisArriInd(Short chassisArriInd) {
        this.chassisArriInd = chassisArriInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.CHASSIS_ARRI_TIMEOUT
     *
     * @return the value of ARMGJOBQ.CHASSIS_ARRI_TIMEOUT
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Short getChassisArriTimeout() {
        return chassisArriTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.CHASSIS_ARRI_TIMEOUT
     *
     * @param chassisArriTimeout the value for ARMGJOBQ.CHASSIS_ARRI_TIMEOUT
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setChassisArriTimeout(Short chassisArriTimeout) {
        this.chassisArriTimeout = chassisArriTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.PICKUP_IND
     *
     * @return the value of ARMGJOBQ.PICKUP_IND
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public String getPickupInd() {
        return pickupInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.PICKUP_IND
     *
     * @param pickupInd the value for ARMGJOBQ.PICKUP_IND
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setPickupInd(String pickupInd) {
        this.pickupInd = pickupInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.PICKUP_TIME
     *
     * @return the value of ARMGJOBQ.PICKUP_TIME
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Date getPickupTime() {
        return pickupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.PICKUP_TIME
     *
     * @param pickupTime the value for ARMGJOBQ.PICKUP_TIME
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setPickupTime(Date pickupTime) {
        this.pickupTime = pickupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.JOB_FINISH_IND
     *
     * @return the value of ARMGJOBQ.JOB_FINISH_IND
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public String getJobFinishInd() {
        return jobFinishInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.JOB_FINISH_IND
     *
     * @param jobFinishInd the value for ARMGJOBQ.JOB_FINISH_IND
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setJobFinishInd(String jobFinishInd) {
        this.jobFinishInd = jobFinishInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.JOB_FINISH_TIME
     *
     * @return the value of ARMGJOBQ.JOB_FINISH_TIME
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Date getJobFinishTime() {
        return jobFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.JOB_FINISH_TIME
     *
     * @param jobFinishTime the value for ARMGJOBQ.JOB_FINISH_TIME
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setJobFinishTime(Date jobFinishTime) {
        this.jobFinishTime = jobFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.TIME_ELAPSED
     *
     * @return the value of ARMGJOBQ.TIME_ELAPSED
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Integer getTimeElapsed() {
        return timeElapsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.TIME_ELAPSED
     *
     * @param timeElapsed the value for ARMGJOBQ.TIME_ELAPSED
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setTimeElapsed(Integer timeElapsed) {
        this.timeElapsed = timeElapsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.ERROR_CODE
     *
     * @return the value of ARMGJOBQ.ERROR_CODE
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Integer getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.ERROR_CODE
     *
     * @param errorCode the value for ARMGJOBQ.ERROR_CODE
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setErrorCode(Integer errorCode) {
        this.errorCode = errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.MODIFY_DATE
     *
     * @return the value of ARMGJOBQ.MODIFY_DATE
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.MODIFY_DATE
     *
     * @param modifyDate the value for ARMGJOBQ.MODIFY_DATE
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.MODIFY_USER
     *
     * @return the value of ARMGJOBQ.MODIFY_USER
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.MODIFY_USER
     *
     * @param modifyUser the value for ARMGJOBQ.MODIFY_USER
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.RFID_NO_ACTUAL
     *
     * @return the value of ARMGJOBQ.RFID_NO_ACTUAL
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public String getRfidNoActual() {
        return rfidNoActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.RFID_NO_ACTUAL
     *
     * @param rfidNoActual the value for ARMGJOBQ.RFID_NO_ACTUAL
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setRfidNoActual(String rfidNoActual) {
        this.rfidNoActual = rfidNoActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMGJOBQ.JOB_CREATE_TIME
     *
     * @return the value of ARMGJOBQ.JOB_CREATE_TIME
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public Date getJobCreateTime() {
        return jobCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMGJOBQ.JOB_CREATE_TIME
     *
     * @param jobCreateTime the value for ARMGJOBQ.JOB_CREATE_TIME
     *
     * @mbg.generated Mon Nov 12 11:49:39 GMT+08:00 2018
     */
    public void setJobCreateTime(Date jobCreateTime) {
        this.jobCreateTime = jobCreateTime;
    }
}